Rererence

drug_DUR_list 

https://ec.europa.eu/health/documents/community-register/html/reg_hum_atc.htm
https://www.drugsafe.or.kr/iwt/ds/ko/useinfo/EgovDurUds.do?pageCsf=KR

# Mount & Import

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
from pandas.api.types import is_numeric_dtype
from pandas.api.types import is_string_dtype
import os
import tensorflow as tf
from tensorflow import keras
import re, glob

In [ ]:
!pwd

/content

In [3]:
cd /content/drive/Shareddrives/Codepresso_8/Drug_list/final_data

/content/drive/Shareddrives/Codepresso_8/Drug_list/final_data

# Check image file

In [4]:
img_base_path = "/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_rximage/images/gallery/300/"

In [5]:
img_pill_path = "/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/"

In [6]:
rxi_path = glob.glob(os.path.join(img_base_path, '*.jpg'))

In [7]:
pill_path = glob.glob(os.path.join(img_pill_path, '*.jpg'))

In [8]:
pill_df = pd.read_excel("/content/drive/Shareddrives/Codepresso_8/rximage_set/directory_info/directory_consumer_grade_images.xlsx")

In [10]:
rxi_info = pd.read_csv('/content/drive/Shareddrives/Codepresso_8/Drug_list/final_data/rxi_info3.csv', index_col=0)

In [11]:
len(rxi_info.drug.unique()), len(rxi_path), len(rxi_info.name.unique()), rxi_info.shape

(195, 8784, 571, (970, 15))

In [ ]:
pill_df['drug'] = pill_df['Name'].apply(lambda x : x.split(" ")[0].lower())

In [ ]:
#rxi_info2['drug'] = 
pill_df['drug'] = pill_df['Name'].apply(lambda x : re.search('[A-Z|a-z|]{3,}', x).group(0).rstrip(' ').lower())

In [ ]:
len(pill_df['drug'].unique())

1062

In [ ]:
len(pill_df['drug'].unique())

1010

In [ ]:
len(pill_path), len(rxi_path)

(8693, 8784)

In [ ]:
os.path.basename(rxi_path[0])
os.path.basename(rxi_path[-1])

'12496-1283-02_RXNAVIMAGE10_281D940C.jpg'

In [ ]:
for i in range(10):
  print(os.path.basename(rxi_path[i]))

00555-9066-67_NLMIMAGE10_17368BB4.jpg
00555-9066-67_NLMIMAGE10_1B368DC4.jpg
00555-9064-58_NLMIMAGE10_08368464.jpg
00555-9064-58_NLMIMAGE10_0E368734.jpg
51285-0081-98_NLMIMAGE10_FF367FE3.jpg
51285-0081-98_NLMIMAGE10_04368254.jpg
51285-0084-98_NLMIMAGE10_F6367B33.jpg
51285-0084-98_NLMIMAGE10_FB367DA3.jpg
00555-9050-58_NLMIMAGE10_9A36CD56.jpg
00555-9050-58_NLMIMAGE10_9E36CF66.jpg

In [ ]:
rxi_file_list = []
for i in range(len(rxi_path)):
  rxi_file_list.append(os.path.basename(rxi_path[i]))

In [ ]:
len(rxi_file_list)

8784

In [ ]:
rxi_target_pre = pd.read_csv("./rxi_info_target3.csv")

In [ ]:
!ls

dg_pr.csv		  drug_dupliation.csv  relation_1_adr.csv
drug_class_m4_dropna.csv  dup_dg_pr.csv        relation_m2.csv
drug_class_m5.csv	  durr.csv	       rxi_info_target3.csv
drug_class_m6.csv	  patient_m3.csv       rxi_info_target3.gsheet

In [ ]:
rxi_target = pd.read_csv("./rxi_meta_target.csv")

In [ ]:
len(rxi_target_pre.drug.unique()), len(rxi_target.drug.unique())

(33, 56)

In [ ]:
len(rxi_info2.drug.unique())

195

In [ ]:
rxi_meta.head(3)

   Unnamed: 0          ndc11  ...     drug2     drug3
0           0  63459-0502-30  ...  fentanyl  fentanyl
1           1  63459-0504-30  ...  fentanyl  fentanyl
2           2  63459-0506-30  ...  fentanyl  fentanyl

[3 rows x 17 columns]

In [ ]:
rxi_path[-20:-10], pill_path[:10]

(['/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_rximage/images/gallery/300/00093-0039-01_RXNAVIMAGE10_4F29A7CD.jpg',
  '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_rximage/images/gallery/300/60505-3251-06_RXNAVIMAGE10_E34AF197.jpg',
  '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_rximage/images/gallery/300/63304-0192-30_RXNAVIMAGE10_9544CA96.jpg',
  '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_rximage/images/gallery/300/63304-0191-30_RXNAVIMAGE10_AA405562.jpg',
  '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_rximage/images/gallery/300/00093-2068-01_RXNAVIMAGE10_A2405112.jpg',
  '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_rximage/images/gallery/300/66993-0057-02_RXNAVIMAGE10_1C4F8E2C.jpg',
  '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_rximage/images/gallery/300/23155-0248-01_RXNAVIMAGE10_043D0258.jpg',
  '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_rximage/images/gallery/300/23155-0246-01_RXNAVIMAGE10_093D04C8.jpg',
  '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_rximage/images/gallery/300/51285-0060-01_RXNAVIMAGE10_6838B465.jpg',
  '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_rximage/images/gallery/300/51285-0061-01_RXNAVIMAGE10_A73BD3BE.jpg'],
 ['/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67253-0320-10_F008F857.jpg',
  '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67253-0391-50_NLMIMAGE10_81404092.jpg',
  '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67253-0462-50_BA03DD2E.jpg',
  '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67253-0700-06_BB0EDD86.jpg',
  '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67253-0741-50_7915BCDD.jpg',
  '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67253-0900-11_4104A0C5.jpg',
  '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67253-0902-10_AC15561A.jpg',
  '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/672530011.jpg',
  '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/672530101.jpg',
  '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/672530140.jpg'])

In [ ]:
os.path.join(img_base_path, "120")

'/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_rximage/images/gallery/300/120'

In [ ]:
!ls os.path.join(img_base_path, "120") | wc -l

/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `ls os.path.join(img_base_path, "120") | wc -l'

In [ ]:
ls /content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_rximage/images/gallery/600 | wc -l

8784

In [ ]:
ls /content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_rximage/images/gallery/300 | wc -l

8784

In [ ]:
rxi.head()

           ndc11  ...                                    RXBASE ORIGINAL
0  00093-0311-01  ...  image/images/gallery/original/00093-0311-01_NL...
1  00093-3165-01  ...  image/images/gallery/original/00093-3165-01_NL...
2  00093-0810-01  ...  image/images/gallery/original/00093-0810-01_NL...
3  00093-0811-01  ...  image/images/gallery/original/00093-0811-01_NL...
4  00093-0812-01  ...  image/images/gallery/original/00093-0812-01_NL...

[5 rows x 18 columns]

In [ ]:
rxi_info2.imprint

0        actiq;200
1        actiq;400
2        actiq;600
3        actiq;800
4       actiq;1200
           ...
4187       wpi;845
4198            sv
4236       wpi;844
4254        832;50
4268         p;300
Name: imprint, Length: 970, dtype: object

In [ ]:
len(set(rxi.nlmImageFileName).union(set(rxi.nlmImageFileName)))

4302

In [ ]:
rxi

In [ ]:
rxi_img_list = set(rxi.nlmImageFileName).union(set(rxi.nlmImageFileName))

In [ ]:
rxi_meta_list = set(rxi_meta.nlmImageFileName).union(set(rxi_meta.nlmImageFileName))

In [ ]:
len(set(rxi_list)), len(set(rxi_img_list)), len(set(rxi_meta_list))

(8784, 4302, 4362)

In [ ]:
len(set(rxi_file_list).intersection(rxi_meta_list)), len(set(rxi_list).intersection(rxi_img_list).intersection(rxi_meta_list)), len(set(rxi_list).intersection(rxi_img_list)), len(set(rxi_list).intersection(rxi_meta_list)), len(set(rxi_img_list).intersection(rxi_meta_list))

(4362, 0, 0, 0, 4302)

In [ ]:
len(rxi_list)

56

In [ ]:
rxi_file = set(rxi_list).intersection(rxi_img_list).intersection(rxi_meta_list)

In [ ]:
frxi_meta_target = rxi_meta[rxi_meta['nlmImageFileName'].isin(rxi_file)]

In [ ]:
rxi_info[rxi_info['nlmImageFileName'].isin(rxi_file)].shape

(970, 14)

In [ ]:
rxi_file_target = rxi[rxi['nlmImageFileName'].isin(rxi_file)]

In [ ]:
len(set(rxi_file_target.drug))

512

In [ ]:
len(target_list)

107

In [ ]:
len(set(rxi_file_target[rxi_file_target['drug'].isin(target_list)].drug))

93

In [ ]:
rxi_target_list = rxi_file_target[rxi_file_target['drug'].isin(target_list)].drug

In [ ]:
rxi_target_list

6               Hydroxyzine
7               Hydroxyzine
8       Hydrochlorothiazide
15      Hydrochlorothiazide
19             Indomethacin
               ...
4356             Famotidine
4358                Aspirin
4359                Aspirin
4360              Ibuprofen
4370            Methimazole
Name: drug, Length: 1370, dtype: object

In [ ]:
rxi_target_list.to_csv('./rxi_target_list.csv', sep=',', index=False)

In [ ]:
rxi_file_target[rxi_file_target['drug'].isin(target_list)].to_csv('./rxi_file_target.csv', index = False)

In [ ]:
rxi_info_target= pd.merge(rxi_file_target, rxi_info, on='ndc11', how = 'outer')

In [ ]:
rxi_file_target = rxi_file_target[rxi_file_target['drug'].isin(target_list)][['ndc11',	'name',	'rxnavImageFileName',	'nlmImageFileName',	'RXNAV 300']]

In [ ]:
rxi_file_target

              ndc11  ...                                          RXNAV 300
6     00185-0615-01  ...  image/images/gallery/300/00185-0615-01_RXNAVIM...
7     00185-0613-01  ...  image/images/gallery/300/00185-0613-01_RXNAVIM...
8     00603-3855-21  ...  image/images/gallery/300/00603-3855-21_RXNAVIM...
15    00781-2074-01  ...  image/images/gallery/300/00781-2074-01_RXNAVIM...
19    00378-0143-01  ...  image/images/gallery/300/00378-0143-01_RXNAVIM...
...             ...  ...                                                ...
4356  62037-0956-10  ...  image/images/gallery/300/62037-0956-10_RXNAVIM...
4358  50844-0249-33  ...  image/images/gallery/300/50844-0249-33_RXNAVIM...
4359  50844-0157-12  ...  image/images/gallery/300/50844-0157-12_RXNAVIM...
4360  50844-0291-08  ...  image/images/gallery/300/50844-0291-08_RXNAVIM...
4370  64376-0655-01  ...  image/images/gallery/300/64376-0655-01_RXNAVIM...

[1370 rows x 5 columns]

In [ ]:
rxi_info_target2 = rxi_info_target[['ndc11',	'name_x',	'rxnavImageFileName_x',	'nlmImageFileName_x',	'RXNAV 300',	'shape',	'size',	'color',	'imprint',	'imprintColor',	'imprintType',	'symbol',	'drug']]

In [ ]:
rxi_info_target2.columns = ['ndc11',	'name',	'rxnavImageFileName',	'nlmImageFileName',	'path_300',	'shape',	'size',	'color',	'imprint',	'imprintColor',	'imprintType',	'symbol',	'drug']

In [ ]:
rxi_info_target2.shape

(2122, 13)

In [ ]:
rxi_info_target3 = rxi_info_target2.dropna(axis = 0)
rxi_info_target3['drug'] = rxi_info_target3['name'].apply(lambda x : x.split(' ')[0])

def drug_name(x):
  re.search('[A-Z|a-z|]{3,}[A-Z|a-z|\s]{3,}', x)
rxi_info_target3['drug2'] = rxi_info_target3['name'].apply(lambda x : drug_name(x))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
rxi_info_target3['drug2'] = rxi_info_target3['name'].apply(lambda x : re.search('[A-Z|a-z|]{3,}[A-Z|a-z|\s]{3,}', x).group().rstrip(' '))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
rxi_info_target3['file'] = rxi_info_target3['path_300'].apply(lambda x : x.split('/')[-1])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
rxi_info_target3

              ndc11  ...                                     file
0     00185-0615-01  ...  00185-0615-01_RXNAVIMAGE10_4F34A795.jpg
1     00185-0613-01  ...  00185-0613-01_RXNAVIMAGE10_F634FB07.jpg
2     00603-3855-21  ...  00603-3855-21_RXNAVIMAGE10_8B34C5C6.jpg
3     00781-2074-01  ...  00781-2074-01_RXNAVIMAGE10_9D34CEF6.jpg
4     00378-0143-01  ...  00378-0143-01_RXNAVIMAGE10_8221411A.jpg
...             ...  ...                                      ...
1320  59467-0318-01  ...  59467-0318-01_RXNAVIMAGE10_BA505D52.jpg
1321  55111-0129-60  ...  55111-0129-60_RXNAVIMAGE10_B051D81E.jpg
1330  63304-0240-01  ...  63304-0240-01_RXNAVIMAGE10_4D3DA69D.jpg
1331  13913-0008-11  ...  13913-0008-11_RXNAVIMAGE10_40402001.jpg
1353  61269-0210-90  ...  61269-0210-90_RXNAVIMAGE10_994D4CFA.jpg

[250 rows x 15 columns]

In [ ]:
rxi_info_target3.to_csv('./rxi_info_target3.csv', index=False)

In [ ]:
rxi_info_target3 = pd.read_csv('./rxi_info_target3.csv', sep = ',')

In [ ]:
rxi_info_target3.drug.unique()

array(['Hydroxyzine', 'Hydrochlorothiazide', 'Indomethacin',
       'Amoxicillin', 'Clindamycin', 'Doxycycline', 'Omeprazole',
       'Phenytoin', 'Ramipril', 'Acyclovir', 'Terazosin', 'Nitroglycerin',
       'Amlodipine', 'Aspirin', 'Acetaminophen', 'Fenofibrate',
       'Ranitidine', 'Budesonide', 'Dutasteride', 'Esomeprazole',
       'Phentermine', 'Tretinoin', 'Metronidazole', 'Isotretinoin',
       'Lithium', 'Nifedipine', 'Naproxen', 'Calcitriol', 'Diclofenac',
       'Hydroxychloroquine', 'Docusate', 'Fentanyl', 'Colchicine'],
      dtype=object)

In [ ]:
rxi_info_target3.drug2.unique()

array(['Hydroxyzine Pamoate', 'Hydrochlorothiazide', 'Indomethacin',
       'Amoxicillin', 'Clindamycin', 'Doxycycline Monohydrate',
       'Omeprazole', 'Phenytoin sodium', 'Ramipril', 'Acyclovir',
       'Terazosin', 'Nitroglycerin', 'Amlodipine', 'Aspirin',
       'Acetaminophen', 'Fenofibrate', 'Ranitidine', 'Budesonide',
       'Dutasteride', 'Esomeprazole', 'Phentermine Hydrochloride',
       'Tretinoin', 'Metronidazole', 'Isotretinoin', 'Lithium Carbonate',
       'Nifedipine', 'Naproxen', 'Calcitriol', 'Diclofenac Sodium',
       'Hydroxychloroquine Sulfate', 'Docusate Sodium', 'Fentanyl',
       'Colchicine', 'Diclofenac Potassium'], dtype=object)

In [ ]:
len(rxi_info_target3.drug.unique())

33

In [ ]:
rxi_info[rxi_info['nlmImageFileName'].isin(rxi_file)]

              ndc11  ...                                               drug
0     63459-0502-30  ...  <re.Match object; span=(0, 9), match='Fentanyl '>
1     63459-0504-30  ...  <re.Match object; span=(0, 9), match='Fentanyl '>
2     63459-0506-30  ...  <re.Match object; span=(0, 9), match='Fentanyl '>
3     63459-0508-30  ...  <re.Match object; span=(0, 9), match='Fentanyl '>
4     63459-0512-30  ...  <re.Match object; span=(0, 9), match='Fentanyl '>
...             ...  ...                                                ...
4187  10370-0191-05  ...  <re.Match object; span=(6, 16), match='Glipizi...
4198  00032-1708-01  ...  <re.Match object; span=(0, 13), match='Progest...
4236  10370-0190-01  ...  <re.Match object; span=(6, 16), match='Glipizi...
4254  00832-0302-00  ...  <re.Match object; span=(0, 29), match='Chlorpr...
4268  64980-0205-01  ...  <re.Match object; span=(0, 18), match='Lithium...

[970 rows x 14 columns]

In [ ]:
rxi_meta[rxi_meta['rxnavImageFileName'].isin(rxi_file)].shape

(0, 35)

In [ ]:
rxi_meta

                                       _id  ... splVersion
0     {'$oid': '5a32f687eb4525ea9e82bee3'}  ...        NaN
1     {'$oid': '5a32f687eb4525ea9e82bee4'}  ...        NaN
2     {'$oid': '5a32f687eb4525ea9e82bee5'}  ...        NaN
3     {'$oid': '5a32f687eb4525ea9e82bee6'}  ...        NaN
4     {'$oid': '5a32f687eb4525ea9e82bee7'}  ...        NaN
...                                    ...  ...        ...
4387  {'$oid': '5a32f6b6eb4525ea9e82d006'}  ...        6.0
4388  {'$oid': '5a32f6b6eb4525ea9e82d007'}  ...        6.0
4389  {'$oid': '5a32f6b6eb4525ea9e82d008'}  ...        6.0
4390  {'$oid': '5a32f6b6eb4525ea9e82d009'}  ...        NaN
4391  {'$oid': '5a32f6b6eb4525ea9e82d00a'}  ...        3.0

[4392 rows x 35 columns]

In [ ]:
len(set(rxi_list).intersection(rxi_meta_list))

4302

In [ ]:
pill= pd.read_excel("/content/drive/Shareddrives/Codepresso_8/rximage_set/directory_info/directory_consumer_grade_images.xlsx")

In [ ]:
pill['file'] = pill.Image.apply(lambda x: x.split('/')[-1])

In [ ]:
pill_path

['/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67253-0320-10_F008F857.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67253-0391-50_NLMIMAGE10_81404092.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67253-0462-50_BA03DD2E.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67253-0700-06_BB0EDD86.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67253-0741-50_7915BCDD.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67253-0900-11_4104A0C5.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67253-0902-10_AC15561A.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/672530011.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/672530101.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/672530140.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/672530180.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/672530181.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/672530201.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/672530380.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/672530381.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/672530382.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/672530383.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/672530388.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/672530660.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/672530820.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/672530901.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/672530903.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67386-0315-01_NLMIMAGE10_123F892C.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/673860301.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/673860303.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/673860310.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/673860311.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/673860312.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/673860314.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67405-0500-10_NLMIMAGE10_0047805C.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/674050543.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/674050575.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/674050577.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/674050650.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/674050671.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440002.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440005.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440003.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440012.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440021.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440023.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440024.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440025.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440026.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440038.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440052.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440057.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440060.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440061.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440075.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440078.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440080.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440085.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440087.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440097.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440102.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440117.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440127.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440136.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440142.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440154.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440161.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440189.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440191.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440194.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440195.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440204.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440206.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440217.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440224.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440225.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440236.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440237.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440247.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440250.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440251.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440252.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440253.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440261.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440268.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440269.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440273.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440276.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440287.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440289.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440290.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440301.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440302.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440306.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440318.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440322.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440326.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440332.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440338.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440346.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440349.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440353.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440354.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440355.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440356.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440371.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440373.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440394.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440397.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440401.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440403.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440404.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440408.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440412.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440431.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440456.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440464.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440468.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440474.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440475.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440479.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440507.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440510.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440511.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440512.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440524.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440534.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440562.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440563.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440564.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440567.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440568.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440570.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440581.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440627.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440629.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440655.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440656.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440662.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440670.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440697.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440700.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440720.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440725.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440747.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440750.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440840.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440848.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440870.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440879.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440882.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440883.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440884.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440885.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440886.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440887.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440888.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440889.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440890.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440891.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440892.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440899.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440911.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440982.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675440988.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/675460111.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/676180100.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67767-0133-60_26269354.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/677670135.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/677670141.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/677670142.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/677670151.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/677670153.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/677670171.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/677670202.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/677810251.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/677810252.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/678570700.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/678570701.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67877-0147-01_NLMIMAGE10_D61DEB0F.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67877-0169-30_NLMIMAGE10_4B4A2591.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67877-0197-05_NLMIMAGE10_914948BA.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67877-0216-60_D807EC3F.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67877-0222-05_NLMIMAGE10_2A3B1538.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67877-0223-05_NLMIMAGE10_274093D4.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67877-0224-05_NLMIMAGE10_2A3B1508.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67877-0294-05_NLMIMAGE10_9140C8C6.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67877-0295-05_NLMIMAGE10_9640CB36.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67877-0296-05_NLMIMAGE10_9A40CD46.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/678770105.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/678770106.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67cebb68-5ab8-0e60-e053-2991aa0a0fbe.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/67e774a6-c9aa-11e2-e053-2991aa0ac1d1.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/68001-0206-00_NLMIMAGE10_DA46ED27.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/680010254.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/68012-0104-30_EE1DF76F.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/68012-0258-20_C91364AB.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/68012-0495-90_NLMIMAGE10_A649D34E.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/680120002.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/680120003.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/680120309.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/680840079.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/680840181.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/680840180.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/680840182.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/680840213.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/680840256.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/680840292.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/680840293.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/680840340.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/680840436.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/680840457.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/680840586.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/68180-0104-09_NLMIMAGE10_893D44EA.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/68180-0112-16_3A091D48.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/68180-0113-16_37081BA0.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/68180-0114-16_35081AE0.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/68180-0115-07_3A081D50.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/68180-0115-07_NLMIMAGE10_3A081D50.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/68180-0117-07_36161B20.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/68180-0121-02_NLMIMAGE10_433DA1BD.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/68180-0185-06_NLMIMAGE10_B33BD98E.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/68180-0216-09_37089BE4.jpg',
 '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_pillbox/68180-0221-01_NLMIMAGE10_4B3C25D1.jpg',

In [ ]:
plist = []
for i in range(4):
  plist.append(os.path.basename(pill_path[i]))

In [ ]:
len(pill_path)

8693

In [ ]:
for i in range(len(pill_path)):
  os.path.basename(pill_path[i])

In [ ]:
pill_list = []
for i in range(len(pill_path)):
  pill_list.append(os.path.basename(pill_path[i]))

In [ ]:
rxi_list = []
for i in range(len(rxi_path)):
  rxi_list.append(os.path.basename(rxi_path[i]))

In [ ]:
len(set(pill.file).intersection(set(pill_list)))

0

In [ ]:
pill_list

['67253-0320-10_F008F857.jpg',
 '67253-0391-50_NLMIMAGE10_81404092.jpg',
 '67253-0462-50_BA03DD2E.jpg',
 '67253-0700-06_BB0EDD86.jpg',
 '67253-0741-50_7915BCDD.jpg',
 '67253-0900-11_4104A0C5.jpg',
 '67253-0902-10_AC15561A.jpg',
 '672530011.jpg',
 '672530101.jpg',
 '672530140.jpg',
 '672530180.jpg',
 '672530181.jpg',
 '672530201.jpg',
 '672530380.jpg',
 '672530381.jpg',
 '672530382.jpg',
 '672530383.jpg',
 '672530388.jpg',
 '672530660.jpg',
 '672530820.jpg',
 '672530901.jpg',
 '672530903.jpg',
 '67386-0315-01_NLMIMAGE10_123F892C.jpg',
 '673860301.jpg',
 '673860303.jpg',
 '673860310.jpg',
 '673860311.jpg',
 '673860312.jpg',
 '673860314.jpg',
 '67405-0500-10_NLMIMAGE10_0047805C.jpg',
 '674050543.jpg',
 '674050575.jpg',
 '674050577.jpg',
 '674050650.jpg',
 '674050671.jpg',
 '675440002.jpg',
 '675440005.jpg',
 '675440003.jpg',
 '675440012.jpg',
 '675440021.jpg',
 '675440023.jpg',
 '675440024.jpg',
 '675440025.jpg',
 '675440026.jpg',
 '675440038.jpg',
 '675440052.jpg',
 '675440057.jpg',
 '675440060.jpg',
 '675440061.jpg',
 '675440075.jpg',
 '675440078.jpg',
 '675440080.jpg',
 '675440085.jpg',
 '675440087.jpg',
 '675440097.jpg',
 '675440102.jpg',
 '675440117.jpg',
 '675440127.jpg',
 '675440136.jpg',
 '675440142.jpg',
 '675440154.jpg',
 '675440161.jpg',
 '675440189.jpg',
 '675440191.jpg',
 '675440194.jpg',
 '675440195.jpg',
 '675440204.jpg',
 '675440206.jpg',
 '675440217.jpg',
 '675440224.jpg',
 '675440225.jpg',
 '675440236.jpg',
 '675440237.jpg',
 '675440247.jpg',
 '675440250.jpg',
 '675440251.jpg',
 '675440252.jpg',
 '675440253.jpg',
 '675440261.jpg',
 '675440268.jpg',
 '675440269.jpg',
 '675440273.jpg',
 '675440276.jpg',
 '675440287.jpg',
 '675440289.jpg',
 '675440290.jpg',
 '675440301.jpg',
 '675440302.jpg',
 '675440306.jpg',
 '675440318.jpg',
 '675440322.jpg',
 '675440326.jpg',
 '675440332.jpg',
 '675440338.jpg',
 '675440346.jpg',
 '675440349.jpg',
 '675440353.jpg',
 '675440354.jpg',
 '675440355.jpg',
 '675440356.jpg',
 '675440371.jpg',
 '675440373.jpg',
 '675440394.jpg',
 '675440397.jpg',
 '675440401.jpg',
 '675440403.jpg',
 '675440404.jpg',
 '675440408.jpg',
 '675440412.jpg',
 '675440431.jpg',
 '675440456.jpg',
 '675440464.jpg',
 '675440468.jpg',
 '675440474.jpg',
 '675440475.jpg',
 '675440479.jpg',
 '675440507.jpg',
 '675440510.jpg',
 '675440511.jpg',
 '675440512.jpg',
 '675440524.jpg',
 '675440534.jpg',
 '675440562.jpg',
 '675440563.jpg',
 '675440564.jpg',
 '675440567.jpg',
 '675440568.jpg',
 '675440570.jpg',
 '675440581.jpg',
 '675440627.jpg',
 '675440629.jpg',
 '675440655.jpg',
 '675440656.jpg',
 '675440662.jpg',
 '675440670.jpg',
 '675440697.jpg',
 '675440700.jpg',
 '675440720.jpg',
 '675440725.jpg',
 '675440747.jpg',
 '675440750.jpg',
 '675440840.jpg',
 '675440848.jpg',
 '675440870.jpg',
 '675440879.jpg',
 '675440882.jpg',
 '675440883.jpg',
 '675440884.jpg',
 '675440885.jpg',
 '675440886.jpg',
 '675440887.jpg',
 '675440888.jpg',
 '675440889.jpg',
 '675440890.jpg',
 '675440891.jpg',
 '675440892.jpg',
 '675440899.jpg',
 '675440911.jpg',
 '675440982.jpg',
 '675440988.jpg',
 '675460111.jpg',
 '676180100.jpg',
 '67767-0133-60_26269354.jpg',
 '677670135.jpg',
 '677670141.jpg',
 '677670142.jpg',
 '677670151.jpg',
 '677670153.jpg',
 '677670171.jpg',
 '677670202.jpg',
 '677810251.jpg',
 '677810252.jpg',
 '678570700.jpg',
 '678570701.jpg',
 '67877-0147-01_NLMIMAGE10_D61DEB0F.jpg',
 '67877-0169-30_NLMIMAGE10_4B4A2591.jpg',
 '67877-0197-05_NLMIMAGE10_914948BA.jpg',
 '67877-0216-60_D807EC3F.jpg',
 '67877-0222-05_NLMIMAGE10_2A3B1538.jpg',
 '67877-0223-05_NLMIMAGE10_274093D4.jpg',
 '67877-0224-05_NLMIMAGE10_2A3B1508.jpg',
 '67877-0294-05_NLMIMAGE10_9140C8C6.jpg',
 '67877-0295-05_NLMIMAGE10_9640CB36.jpg',
 '67877-0296-05_NLMIMAGE10_9A40CD46.jpg',
 '678770105.jpg',
 '678770106.jpg',
 '67cebb68-5ab8-0e60-e053-2991aa0a0fbe.jpg',
 '67e774a6-c9aa-11e2-e053-2991aa0ac1d1.jpg',
 '68001-0206-00_NLMIMAGE10_DA46ED27.jpg',
 '680010254.jpg',
 '68012-0104-30_EE1DF76F.jpg',
 '68012-0258-20_C91364AB.jpg',
 '68012-0495-90_NLMIMAGE10_A649D34E.jpg',
 '680120002.jpg',
 '680120003.jpg',
 '680120309.jpg',
 '680840079.jpg',
 '680840181.jpg',
 '680840180.jpg',
 '680840182.jpg',
 '680840213.jpg',
 '680840256.jpg',
 '680840292.jpg',
 '680840293.jpg',
 '680840340.jpg',
 '680840436.jpg',
 '680840457.jpg',
 '680840586.jpg',
 '68180-0104-09_NLMIMAGE10_893D44EA.jpg',
 '68180-0112-16_3A091D48.jpg',
 '68180-0113-16_37081BA0.jpg',
 '68180-0114-16_35081AE0.jpg',
 '68180-0115-07_3A081D50.jpg',
 '68180-0115-07_NLMIMAGE10_3A081D50.jpg',
 '68180-0117-07_36161B20.jpg',
 '68180-0121-02_NLMIMAGE10_433DA1BD.jpg',
 '68180-0185-06_NLMIMAGE10_B33BD98E.jpg',
 '68180-0216-09_37089BE4.jpg',
 '68180-0221-01_NLMIMAGE10_4B3C25D1.jpg',
 '68180-0222-01_NLMIMAGE10_503C2841.jpg',
 '68180-0223-01_NLMIMAGE10_6D3F3689.jpg',
 '68180-0311-01_NLMIMAGE10_053B828C.jpg',
 '68180-0312-01_NLMIMAGE10_7D3B3EA9.jpg',
 '68180-0313-01_18078C0C.jpg',
 '68180-0315-06_28081450.jpg',
 '68180-0337-07_NLMIMAGE10_DE3C6F23.jpg',
 '68180-0352-06_NLMIMAGE10_EF3477C3.jpg',
 '68180-0360-09_NLMIMAGE10_17470B88.jpg',
 '68180-0361-09_NLMIMAGE10_E54072D3.jpg',
 '68180-0467-01_3A089D34.jpg',
 '68180-0469-03_3D089EE4.jpg',
 '68180-0478-01_AB21558A.jpg',
 '68180-0479-01_B4215A0A.jpg',
 '68180-0480-01_0A21855C.jpg',
 '68180-0481-01_FA217D1B.jpg',
 '68180-0501-01_08240460.jpg',
 '68180-0502-01_F623FB3F.jpg',
 '68180-0513-03_3F199F8C.jpg',
 '68180-0516-02_10088804.jpg',
 '68180-0518-01_070883B4.jpg',
 '68180-0519-02_19088CB4.jpg',
 '68180-0520-02_16088B04.jpg',
 '68180-0554-09_NLMIMAGE10_9B474DBA.jpg',
 '68180-0557-09_C20E6163.jpg',
 '68180-0558-09_BC0E5E62.jpg',
 '68180-0559-09_C00E6013.jpg',
 '68180-0568-01_NLMIMAGE10_9741CB8E.jpg',
 '68180-0590-02_NLMIMAGE10_6F473799.jpg',
 '68180-0591-02_AE0ED726.jpg',
 '68180-0598-01_NLMIMAGE10_783FBC6D.jpg',
 '68180-0711-60_BB135DBA.jpg',
 '68180-0756-01_NLMIMAGE10_473DA3FD.jpg',
 '68180-0757-01_NLMIMAGE10_553DAAED.jpg',
 '68180-0758-01_NLMIMAGE10_483DA45D.jpg',
 '68180-0759-01_NLMIMAGE10_3C3E9E74.jpg',
 '68180-0760-01_NLMIMAGE10_513DA8DD.jpg',
 '681800122.jpg',
 '681800180.jpg',
 '681800280.jpg',
 '681800302.jpg',
 '681800303.jpg',
 '681800351.jpg',
 '681800353.jpg',
 '681800403.jpg',
 '681800404.jpg',
 '681800412.jpg',
 '681800482.jpg',
 '681800512.jpg',
 '681800514.jpg',
 '681800515.jpg',
 '681800517.jpg',
 '68196-0159-14_NLMIMAGE10_8E38C726.jpg',
 '68220-0085-90_2D1316D8.jpg',
 '682200112.jpg',
 '682200113.jpg',
 '682200115.jpg',
 '682200160.jpg',
 '683080710.jpg',
 '683080775.jpg',
 '68382-0001-16_DE086F73.jpg',
 '68382-0003-01_011300E8.jpg',
 '68382-0005-14_NLMIMAGE10_8B3CC5F6.jpg',
 '68382-0019-01_F8127C53.jpg',
 '68382-0020-01_FB127DA3.jpg',
 '68382-0022-01_59202C81.jpg',
 '68382-0023-01_452022C1.jpg',
 '68382-0024-01_A12050B2.jpg',
 '68382-0040-01_7C0E3E01.jpg',
 '68382-0041-01_740E3A71.jpg',
 '68382-0052-01_3B129D84.jpg',
 '68382-0053-01_3D129ED4.jpg',
 '68382-0054-01_2B1295D4.jpg',
 '68382-0055-01_35129A84.jpg',
 '68382-0056-10_1F128FD4.jpg',
 '68382-0057-01_23129184.jpg',
 '68382-0058-01_251292D4.jpg',
 '68382-0059-01_311298D4.jpg',
 '68382-0064-10_2F129784.jpg',
 '68382-0065-16_310E9884.jpg',
 '68382-0077-16_NLMIMAGE10_F73AFB87.jpg',
 '68382-0078-16_NLMIMAGE10_C54062E3.jpg',
 '68382-0080-01_8407C20E.jpg',
 '68382-0096-05_NLMIMAGE10_F8407C03.jpg',
 '68382-0097-06_D2086973.jpg',
 '68382-0099-06_D6086B23.jpg',
 '68382-0112-14_NLMIMAGE10_4C3D2629.jpg',
 '68382-0113-05_NLMIMAGE10_553D2AD9.jpg',
 '68382-0114-05_NLMIMAGE10_C13F609B.jpg',
 '68382-0115-05_NLMIMAGE10_9D3D4EAA.jpg',
 '68382-0131-01_9D08CEE6.jpg',
 '68382-0135-16_CB16E5D7.jpg',
 '68382-0136-10_2B0895B4.jpg',
 '68382-0137-10_2E089704.jpg',
 '68382-0139-05_NLMIMAGE10_A943548A.jpg',
 '68382-0142-16_310898B4.jpg',
 '68382-0143-16_34089A34.jpg',
 '68382-0180-10_NLMIMAGE10_6A3FB57D.jpg',
 '68382-0182-01_NLMIMAGE10_9A45CD5E.jpg',
 '68382-0183-14_NLMIMAGE10_9545CAEE.jpg',
 '68382-0196-16_AA1C5542.jpg',
 '68382-0197-16_F60DFB6F.jpg',
 '68382-0198-16_FA0DFD1F.jpg',
 '68382-0230-16_NLMIMAGE10_1F3C8FF4.jpg',
 '68382-0261-01_DB12ED97.jpg',
 '68382-0271-14_NLMIMAGE10_E749F38F.jpg',
 '68382-0272-01_NLMIMAGE10_08470408.jpg',
 '68382-0776-01_NLMIMAGE10_75463AD1.jpg',
 '683820036.jpg',
 '683820042.jpg',
 '683820046.jpg',
 '683820050.jpg',
 '683820051.jpg',
 '683820069.jpg',
 '683820081.jpg',
 '683820092.jpg',
 '683820093.jpg',
 '683820094.jpg',
 '683820095.jpg',
 '683820117.jpg',
 '683820123.jpg',
 '683820132.jpg',
 '683820228.jpg',
 '683820266.jpg',
 '683820267.jpg',
 '683820314.jpg',
 '683820315.jpg',
 '683820346.jpg',
 '683820347.jpg',
 '683820761.jpg',
 '683820762.jpg',
 '683820763.jpg',
 '68453-0142-03_A416D256.jpg',
 '684530170.jpg',
 '684530375.jpg',
 '684530777.jpg',
 '684530850.jpg',
 '684530950.jpg',
 '68462-0103-40_6B1B35A9.jpg',
 '68462-0126-05_2807947C.jpg',
 '68462-0127-05_2B0795CC.jpg',
 '68462-0130-01_NLMIMAGE10_783CBC35.jpg',
 '68462-0137-01_B2085922.jpg',
 '68462-0138-01_BA085D72.jpg',
 '68462-0139-01_B8085C22.jpg',
 '68462-0153-10_NLMIMAGE10_9B41CDFE.jpg',
 '68462-0157-13_931B498A.jpg',
 '68462-0158-13_NLMIMAGE10_E440F267.jpg',
 '68462-0159-01_9A23CD1E.jpg',
 '68462-0160-01_B123D88E.jpg',
 '68462-0163-01_DC216E7B.jpg',
 '68462-0179-01_C108E0E7.jpg',
 '68462-0188-01_BF08DF96.jpg',
 '68462-0189-01_BB08DDE6.jpg',
 '68462-0190-05_7B12BD95.jpg',
 '68462-0195-90_000E0010.jpg',
 '68462-0208-01_7A1B3D59.jpg',
 '68462-0209-01_NLMIMAGE10_123C8934.jpg',
 '68462-0223-01_NLMIMAGE10_7F40BFC5.jpg',
 '68462-0224-01_9216C956.jpg',
 '68462-0231-10_NLMIMAGE10_0B45858C.jpg',
 '68462-0233-01_NLMIMAGE10_1E3E0F60.jpg',
 '68462-0235-01_NLMIMAGE10_693B3489.jpg',
 '68462-0248-05_5E12AF25.jpg',
 '68462-0249-20_8E0EC736.jpg',
 '68462-0260-05_19128CD4.jpg',
 '68462-0292-01_NLMIMAGE10_4C3F2609.jpg',
 '68462-0293-05_NLMIMAGE10_F03CF837.jpg',
 '68462-0303-29_NLMIMAGE10_5745AB9D.jpg',
 '68462-0305-84_NLMIMAGE10_E744F3A7.jpg',
 '68462-0329-01_C3126183.jpg',
 '68462-0330-90_NLMIMAGE10_F4497A6B.jpg',
 '68462-0331-90_NLMIMAGE10_F43E7A43.jpg',
 '68462-0332-90_NLMIMAGE10_EF3E77D3.jpg',
 '68462-0333-90_NLMIMAGE10_9B414D8A.jpg',
 '68462-0358-05_A71C53C2.jpg',
 '68462-0359-05_6D1B36F9.jpg',
 '68462-0360-01_06230358.jpg',
 '68462-0361-01_D222E917.jpg',
 '68462-0404-67_NLMIMAGE10_CC39E66F.jpg',
 '68462-0406-10_NLMIMAGE10_2E3B1778.jpg',
 '68462-0461-60_NLMIMAGE10_B73D5B9A.jpg',
 '68462-0474-01_NLMIMAGE10_5047A81D.jpg',
 '68462-0499-76_NLMIMAGE10_AF3CD7F6.jpg',
 '68462-0500-33_NLMIMAGE10_CA3CE547.jpg',
 '68462-0563-01_NLMIMAGE10_BF39DFDE.jpg',
 '684620102.jpg',
 '684620104.jpg',
 '684620146.jpg',
 '684620147.jpg',
 '684620162.jpg',
 '684620164.jpg',
 '684620196.jpg',
 '684620165.jpg',
 '684620197.jpg',
 '684620198.jpg',
 '684620204.jpg',
 '684620207.jpg',
 '684620304.jpg',
 '684620362.jpg',
 '684620425.jpg',
 '684620435.jpg',
 '684620554.jpg',
 '684620555.jpg',
 '68546014256.jpg',
 '68546022956.jpg',
 '68682-0065-10_NLMIMAGE10_A744D396.jpg',
 '68682-0409-10_NLMIMAGE10_6D39B6CD.jpg',
 '68682-0528-01_NLMIMAGE10_943A4A22.jpg',
 '686820101.jpg',
 '686820302.jpg',
 '686820367.jpg',
 '686820368.jpg',
 '686820369.jpg',
 '686820370.jpg',
 '686820371.jpg',
 '686820372.jpg',
 '686820520.jpg',
 '686820519.jpg',
 '686820521.jpg',
 '686820525.jpg',
 '686820705.jpg',
 '686820706.jpg',
 '686820707.jpg',
 '686820709.jpg',
 '686820993.jpg',
 '687270600.jpg',
 '687270601.jpg',
 '687520025.jpg',
 '687520065.jpg',
 '687520090.jpg',
 '68774-0400-01_NLMIMAGE10_D803EC2F.jpg',
 '687740600.jpg',
 '687740601.jpg',
 '688500004.jpg',
 '688500005.jpg',
 '688500010.jpg',
 '688500012.jpg',
 '68968-3500-01_581E2C71.jpg',
 '689682020.jpg',
 '689682040.jpg',
 '689683250.jpg',
 '689684492.jpg',
 '68a1b925-d6b6-490f-e053-2a91aa0ac191.jpg',
 '69097-0122-12_NLMIMAGE10_AD4356FA.jpg',
 '690970225.jpg',
 '69bd5d7d-037b-30ab-e053-2a91aa0a0e06.jpg',
 '69bd5d7d-037e-30ab-e053-2a91aa0a0e06.jpg',
 '6ac2ae68-4a74-6c90-e053-2991aa0a42cb.jpg',
 '6b51d2e4-9b8d-0369-e053-2a91aa0a2500.jpg',
 '6b51fb35-9bbc-41fb-e053-2a91aa0a11de.jpg',
 '6b524ce3-fbaa-f9b0-e053-2991aa0a25a8.jpg',
 '6bdc5a5f-7e54-4e58-e053-2991aa0a054f.jpg',
 '6bde9cfa-31af-0222-e053-2991aa0a6e7d.jpg',
 '6c2f790d-5f08-2726-e053-2991aa0aedca.jpg',
 '6bdf0433-2b41-1ff2-e053-2991aa0a7997.jpg',
 '6c2f7c18-ab2b-e2f5-e053-2991aa0a32e0.jpg',
 '6c2f806d-ec57-c623-e053-2a91aa0af4bb.jpg',
 '6cf5fa73-af2e-881e-e053-2991aa0a7ec6.jpg',
 '6cf666c0-b97b-e03a-e053-2991aa0a3722.jpg',
 '6d996ed0-6e6c-0311-e053-2a91aa0ada14.jpg',
 '6dd74330-3842-0a77-e053-2991aa0a1817.jpg',
 '6e7691d8-5062-6212-e053-2a91aa0ab86d.jpg',
 '6e783ec1-6f0b-7e66-e053-2a91aa0a694f.jpg',
 '6mg_Capsule.jpg',
 '7.5_mg-200_mg_Hydrocodone-IBU_Tablet.jpg',
 '701d9d2b-03b0-2c75-e053-2991aa0a2ebf.jpg',
 '701d9d2b-03b1-2c75-e053-2991aa0a2ebf.jpg',
 '701d9d2b-03b2-2c75-e053-2991aa0a2ebf.jpg',
 '71f9e3bb-e69d-5387-e053-2a95a90a9fc5.jpg',
 '71f9e3bb-e69e-5387-e053-2a95a90a9fc5.jpg',
 '71fbf850-d345-6017-e053-2a95a90a37e4.jpg',
 '71fbf850-d346-6017-e053-2a95a90a37e4.jpg',
 '723bfc96-dd0f-e346-e053-2991aa0abbdb.jpg',
 '723bfc96-dd10-e346-e053-2991aa0abbdb.jpg',
 '72531622-8603-8d5e-e053-2a91aa0abe03.jpg',
 '73a1562f-6f29-c158-e053-2a91aa0abc31.jpg',
 '73a1562f-6f2b-c158-e053-2a91aa0abc31.jpg',
 '750_mg_Tablet.jpg',
 '75987-0010-03_NLMIMAGE10_B439DA0E.jpg',
 '759870030.jpg',
 '759870031.jpg',
 '75_mg_Venlafaxine_Tablet.jpg',
 '76267e0f-fa20-49ec-e053-2991aa0a877a.jpg',
 '762820152.jpg',
 '762820153.jpg',
 '762820200.jpg',
 '762820201.jpg',
 '762820202.jpg',
 '762820206.jpg',
 '762820207.jpg',
 '762820208.jpg',
 '762820209.jpg',
 '762820210.jpg',
 '762820212.jpg',
 '762820213.jpg',
 '762820214.jpg',
 '762820225.jpg',
 '762820228.jpg',
 '762820237.jpg',
 '762820238.jpg',
 '762820239.jpg',
 '762820246.jpg',
 '762820247.jpg',
 '762820249.jpg',
 '762820248.jpg',
 '762820250.jpg',
 '762820251.jpg',
 '762820256.jpg',
 '762820257.jpg',
 '762820258.jpg',
 '762820271.jpg',
 '762820272.jpg',
 '762820273.jpg',
 '762820274.jpg',
 '762820302.jpg',
 '762820327.jpg',
 '762820328.jpg',
 '762820329.jpg',
 '762820330.jpg',
 '762820331.jpg',
 '762820332.jpg',
 '762820333.jpg',
 '762820334.jpg',
 '762820335.jpg',
 '762820377.jpg',
 '762820405.jpg',
 '762820406.jpg',
 '762820412.jpg',
 '762820417.jpg',
 '762820418.jpg',
 '762820419.jpg',
 '762820420.jpg',
 '762820421.jpg',
 '762820422.jpg',
 '763880635.jpg',
 '763880713.jpg',
 '76439-0101-50_NLMIMAGE10_6939B48D.jpg',
 '76439-0102-50_NLMIMAGE10_3A3D9D0C.jpg',
 '76439-0103-50_NLMIMAGE10_793FBC9D.jpg',
 '76439-0123-10_NLMIMAGE10_6A3DB50D.jpg',
 '76439-0124-10_NLMIMAGE10_CA406523.jpg',
 '76439-0125-10_NLMIMAGE10_39409CE4.jpg',
 '76439-0136-11_NLMIMAGE10_3247994C.jpg',
 '76439-0140-90_NLMIMAGE10_B340D9D6.jpg',
 '76439-0141-11_NLMIMAGE10_8440C236.jpg',
 '76439-0302-10_NLMIMAGE10_37459BAC.jpg',
 '764390107.jpg',
 '764390201.jpg',
 '764390217.jpg',
 '764390307.jpg',
 '764390308.jpg',
 '764390309.jpg',
 '764f87fa-dde9-0e97-e053-2991aa0ab4ea.jpg',
 '764f87fa-ddec-0e97-e053-2991aa0ab4ea.jpg',
 '764fb488-042b-58c3-e053-2a91aa0a9813.jpg',
 '7650c4bc-9d9b-dde0-e053-2a91aa0aa20b.jpg',
 '76520727-2175-c982-e053-2991aa0ad090.jpg',
 '76520727-2176-c982-e053-2991aa0ad090.jpg',
 '76522585-bf72-4964-e053-2991aa0af7a8.jpg',
 '77cca432-20ca-9e25-e053-2991aa0a4581.jpg',
 '77ce3b3a-0003-37ac-e053-2991aa0a6af6.jpg',
 '77d03966-c90e-2327-e053-2a91aa0a0d21.jpg',
 '78936619-6e4b-bb58-e053-2991aa0a0e79.jpg',
 '7894bddb-4e7b-4f70-e053-2a91aa0a0cfe.jpg',
 '78b3e3d5-b255-6aca-e053-2a91aa0ac66c.jpg',
 '78d1d0bf-5b3d-947d-e053-2a91aa0ae3f0.jpg',
 '78d2ec83-c576-1eb1-e053-2a91aa0aa179.jpg',
 '78d2efc3-976a-208d-e053-2991aa0ab5d9.jpg',
 '78d2efc3-976b-208d-e053-2991aa0ab5d9.jpg',
 '78d2efc3-976c-208d-e053-2991aa0ab5d9.jpg',
 '78d2efc3-9770-208d-e053-2991aa0ab5d9.jpg',
 '78d2efc3-9771-208d-e053-2991aa0ab5d9.jpg',
 '78d3585e-44cc-748a-e053-2991aa0a5e2c.jpg',
 '7900f895-e48f-282b-e053-2991aa0ace94.jpg',
 '78e62b52-5423-c2dd-e053-2991aa0a4c5a.jpg',
 '78e62b52-5437-c2dd-e053-2991aa0a4c5a.jpg',
 '790c1c5b-f11c-667f-e053-2991aa0a4dbe.jpg',
 '790d3c1e-dc97-488e-e053-2a91aa0ad8cb.jpg',
 '790d4eb9-47f5-f9b3-e053-2991aa0a1c18.jpg',
 '790dd616-e000-53ca-e053-2a91aa0a46f3.jpg',
 '7964b3d9-e4e8-1f1e-e053-2a91aa0acbe3.jpg',
 '7964b3d9-e4e9-1f1e-e053-2a91aa0acbe3.jpg',
 '798e3f77-568e-aac3-e053-2991aa0adaae.jpg',
 '799c111c-2531-f2b1-e053-2a91aa0a9656.jpg',
 '799c0cff-ec6a-7fc6-e053-2991aa0a77ef.jpg',
 '79b89d1f-26f7-8f3c-e053-2991aa0a9065.jpg',
 '79b89d1f-26f8-8f3c-e053-2991aa0a9065.jpg',
 '79b89d1f-26f9-8f3c-e053-2991aa0a9065.jpg',
 '7a19920f-c498-2458-e053-2991aa0a83d4.jpg',
 '7a19920f-c49b-2458-e053-2991aa0a83d4.jpg',
 '7a199817-24f1-3d6d-e053-2991aa0a922f.jpg',
 '7a26f69f-fa5e-9fb0-e053-2a91aa0a3fc8.jpg',
 '7a273b99-d3ab-0730-e053-2a91aa0a3831.jpg',
 '7a275a7b-f373-88e3-e053-2991aa0aa498.jpg',
 '7a2a3a50-3ec8-3844-e053-2991aa0a9248.jpg',
 '7a2a48bb-a028-6ccc-e053-2a91aa0a0013.jpg',
 '7a2a8c6f-d770-378f-e053-2991aa0aeb15.jpg',
 '7a2a8c6f-d772-378f-e053-2991aa0aeb15.jpg',
 '7a2a9577-fb35-e63a-e053-2a91aa0a6f30.jpg',
 '7ab591d2-aa93-d82f-e053-2a91aa0ae870.jpg',
 '7b00fa48-7165-088a-e053-2991aa0aaaa5.jpg',
 '7b0692fd-71d7-bd7d-e053-2a91aa0a3a38.jpg',
 '7b4ba0c5-0287-b7a7-e053-2991aa0a575e.jpg',
 '7b90540f-d68f-1d89-e053-2a91aa0a7c89.jpg',
 '7b90540f-d690-1d89-e053-2a91aa0a7c89.jpg',
 '7b90540f-d692-1d89-e053-2a91aa0a7c89.jpg',
 '7b91949b-f7ab-4a44-e053-2991aa0ab2c1.jpg',
 '7ba85394-c695-6708-e053-2a91aa0a705b.jpg',
 '7ba8adf9-4e62-4d5c-e053-2a91aa0a661e.jpg',
 '7bba24b6-077b-1e43-e053-2a91aa0acf0f.jpg',
 '7bba21e7-dbed-1fd7-e053-2a91aa0accdf.jpg',
 '7bcde04b-267c-1dfa-e053-2991aa0ac48c.jpg',
 '7bcdf1bb-88eb-3a48-e053-2a91aa0a9b05.jpg',
 '7bcdf1bb-88ec-3a48-e053-2a91aa0a9b05.jpg',
 '7be3cc3c-14ec-607b-e053-2a91aa0ab3e0.jpg',
 '7be4bef4-b594-3e19-e053-2a91aa0a6949.jpg',
 '7be4fd48-e084-09d4-e053-2991aa0a2ded.jpg',
 '7c390062-bfcd-57f5-e053-2991aa0af2e6.jpg',
 '7c7105dd-dfe0-688b-e053-2a91aa0a43b6.jpg',
 '7c74ee11-5813-39cd-e053-2a91aa0a5d6c.jpg',
 '7c74ee11-5814-39cd-e053-2a91aa0a5d6c.jpg',
 '7c74f89a-87e8-1073-e053-2991aa0ae062.jpg',
 '7d39b439-fe6d-f341-e053-2991aa0a3d81.jpg',
 '7d39b499-33b9-c3d8-e053-2a91aa0aa147.jpg',
 '7d39b499-33bb-c3d8-e053-2a91aa0aa147.jpg',
 '7d4bfcf9-0c2f-3272-e053-2991aa0af7a7.jpg',
 '7d4c0cb0-8d66-72b1-e053-2a91aa0a6bba.jpg',
 '7d4c0cb0-8d67-72b1-e053-2a91aa0a6bba.jpg',
 '7d4c0cb0-8d68-72b1-e053-2a91aa0a6bba.jpg',
 '7d4c0cb0-8d6b-72b1-e053-2a91aa0a6bba.jpg',
 '7d4c187e-14ba-7c69-e053-2991aa0a3c5d.jpg',
 '7d4d70e5-8c56-5c22-e053-2a91aa0ad97e.jpg',
 '7d4d73f1-5e9a-6eb0-e053-2a91aa0a0bb1.jpg',
 '7d639502-9c8b-9593-e053-2a91aa0a107d.jpg',
 '7d639acf-bb60-b033-e053-2a91aa0af38e.jpg',
 '7d63a697-c7b1-cbe7-e053-2a91aa0a9c7f.jpg',
 '7d76e987-5883-5a68-e053-2991aa0a47e7.jpg',
 '7d770bd7-320a-1da5-e053-2991aa0afa88.jpg',
 '7df287af-652e-ab50-e053-2a91aa0a3e75.jpg',
 '7df2b505-952f-0bd1-e053-2991aa0ad810.jpg',
 '7df2b79e-e940-1048-e053-2991aa0a108b.jpg',
 '7df2c42a-fdaf-a893-e053-2a91aa0a249f.jpg',
 '7df2ec94-b5e7-8aec-e053-2a91aa0a46cf.jpg',
 '7df333d0-332c-62d3-e053-2a91aa0a6111.jpg',
 '7df3366d-aefa-9352-e053-2991aa0a8cab.jpg',
 '7df34d04-0448-42c1-e053-2991aa0a1f8b.jpg',
 '7df35985-5d7e-5e35-e053-2a91aa0a033c.jpg',
 '7df35d1d-0edd-4933-e053-2991aa0ace33.jpg',
 '7e013688-39e7-1676-e053-2a91aa0a64a4.jpg',
 '800_mg_Sevelamer_HCl_Tablet.jpg',
 '80871395-240f-e084-e053-2991aa0a287e.jpg',
 '809f1f83-8bdd-0d86-e053-2a91aa0a85a2.jpg',
 '80_mg_Propranolol_HCl_ER_Capsule.jpg',
 '80_mg_Tablet.jpg',
 '812c8595-ea0c-6ab4-e053-2a91aa0ab89b.jpg',
 '80_mg_Valsartan_Tablet.jpg',
 '812c8595-ea0d-6ab4-e053-2a91aa0ab89b.jpg',
 '813de020-5779-3a2f-e053-2a91aa0ae788.jpg',
 '819ede2e-3471-1539-e053-2991aa0a65f3.jpg',
 '819f8846-7161-463a-e053-2a91aa0a6377.jpg',
 '819f8846-7162-463a-e053-2a91aa0a6377.jpg',
 '81a057d2-f3a0-4b3a-e053-2a91aa0af109.jpg',
 '81a16fa7-2365-7bb7-e053-2a91aa0a2fa3.jpg',
 '823163e2-b271-431d-e053-2991aa0a9ae8.jpg',
 '82537fd4-c86a-bb38-e053-2a91aa0a30ac.jpg',
 '82537fd4-c86b-bb38-e053-2a91aa0a30ac.jpg',
 '8256bd23-5b02-db8e-e053-2991aa0a66d6.jpg',
 '826a83ac-11d9-1364-e053-2991aa0a954f.jpg',
 '826aadb5-a4a6-62b2-e053-2a91aa0a01ed.jpg',
 '826d39d8-99f6-2582-e053-2991aa0af2d4.jpg',

In [ ]:
pill.head()

     NDC11  Part  ...       drug                                 file
0  2322730     1  ...  STRATTERA  CLLLLUPGIX7J8MP1WWQ9WN4-CO0B5NV.CR2
1  2322730     1  ...  STRATTERA   PRNJ-AXZIQ!HUQKJJBP_DV44ST0KN9.CR2
2  2322730     1  ...  STRATTERA   79U-YY6M1UUR6F127ZMACIWPEEXHLB.JPG
3  2322730     1  ...  STRATTERA   7WVFV5H74!ELFNQ_GUH92E9ERM9P2K.JPG
4  2322730     1  ...  STRATTERA  B4CH0R9B7PEQ6GORRX-8XWOL-_G7W9_.JPG

[5 rows x 7 columns]

In [ ]:
pill['drug'] = pill['Name'].apply(lambda x : x.split(" ")[0])

In [ ]:
len(set(pill.drug)), len(set(rxi.drug)), len(set(rxi.drug).intersection((set(pill.drug))))

(1291, 512, 101)

# Read_Data

In [ ]:
dur= pd.read_excel("/content/drive/Shareddrives/Codepresso_8/Drug_list/public_DUR.xlsx")
rxi= pd.read_csv("/content/drive/Shareddrives/Codepresso_8/rximage_set/table.csv", sep = ",")
drug_101= pd.read_excel("/content/drive/Shareddrives/Codepresso_8/Drug_list/101_drug_list_0522.xlsx", sheet_name = 0, header = None)
#com_ph= pd.read_excel("/content/drive/Shareddrives/Codepresso_8/Drug_list/KIDS_DUR/병용금기 성분리스트.xlsx", sheet_name = 0, header = 1, index_col = 0)

liver= pd.read_excel("/content/drive/Shareddrives/Codepresso_8/Drug_list/KIDS_DUR/liver_kidney.xlsx", sheet_name = 'liver', header = 0, index_col = 0)
kidney= pd.read_excel("/content/drive/Shareddrives/Codepresso_8/Drug_list/KIDS_DUR/liver_kidney.xlsx", sheet_name = 'kidney', header = 0, index_col = 0)
#liver = pd.read_csv("/content/drive/Shareddrives/Codepresso_8/Drug_list/KIDS_DUR/liver.txt", sep = '\t')
#kidney = pd.read_csv("/content/drive/Shareddrives/Codepresso_8/Drug_list/KIDS_DUR/kidney.txt", sep = '\t')
top= pd.read_excel("/content/drive/Shareddrives/Codepresso_8/Drug_list/KIDS_DUR/drug_kids_0805.xlsx", sheet_name = 'top300', header = 0, index_col = 0)
preg= pd.read_excel("/content/drive/Shareddrives/Codepresso_8/Drug_list/KIDS_DUR/pregnant.xlsx", header=0, index_col = 0)
kid= pd.read_excel("/content/drive/Shareddrives/Codepresso_8/Drug_list/KIDS_DUR/kid.xlsx", header=0 )
eldery= pd.read_excel("/content/drive/Shareddrives/Codepresso_8/Drug_list/KIDS_DUR/drug_kids_0805.xlsx", sheet_name = 'eldery', header = 0, index_col = 0)

preg_ph= pd.read_excel("/content/drive/Shareddrives/Codepresso_8/Drug_list/KIDS_DUR/임부금기_210726.xlsx", header = 1, index_col = 0)
kid_ph= pd.read_excel("/content/drive/Shareddrives/Codepresso_8/Drug_list/KIDS_DUR/특정연령대금기.xlsx", header = 1, index_col = 0)
com_ph= pd.read_excel("/content/drive/Shareddrives/Codepresso_8/Drug_list/KIDS_DUR/병용금기.xlsx", header = 1, index_col = 0)
period_ph= pd.read_excel("/content/drive/Shareddrives/Codepresso_8/Drug_list/KIDS_DUR/투여기간주의.xlsx", header = 1, index_col = 0)
dup_ph= pd.read_excel("/content/drive/Shareddrives/Codepresso_8/Drug_list/KIDS_DUR/효능군중복주의.xlsx", header = 1, index_col = 0)
eldery_ph= pd.read_excel("/content/drive/Shareddrives/Codepresso_8/Drug_list/KIDS_DUR/노인주의_210726.xlsx", header = 1, index_col = 0)
dg_ph= pd.read_excel("/content/drive/Shareddrives/Codepresso_8/Drug_list/KIDS_DUR/용량주의.xlsx", header = 1, index_col = 0)

In [ ]:
top['drug'] = top['drug'].apply(lambda x : x.split(';')[0])

KeyError: ignored

In [ ]:
dur.head()

   DUR일련번호 DUR유형 단일복합구분코드  ...           병용금기약효분류   비고  상태
0     4050  병용금기       복합  ...        [01130]항전간제  NaN  정상
1     4058  병용금기       복합  ...  [01190]기타의 중추신경용약  NaN  정상
2     4078  병용금기       복합  ...   [06290]기타의 화학요법제  NaN  정상
3     4328  병용금기       복합  ...       [01230]자율신경제  NaN  정상
4     4330  병용금기       복합  ...       [01230]자율신경제  NaN  정상

[5 rows x 26 columns]

In [ ]:
dur.columns

Index(['DUR일련번호', 'DUR유형', '단일복합구분코드', 'DUR성분코드', 'DUR성분명영문', 'DUR성분명', '복합제',
       '관계성분', '약효분류코드', '효능군', '고시일자', '금기내용', '제형', '연령기준', '최대투여기간',
       '1일최대용량', '등급', '병용금기단일복합구분코드', '병용금기DUR성분코드', '병용금기DUR성분명',
       '병용금기DUR성분명.1', '병용금기복합제', '병용금기관계성분', '병용금기약효분류', '비고', '상태'],
      dtype='object')

In [ ]:
durr= dur[['DUR성분코드', 'DUR성분명영문', 'DUR성분명', '복합제', '관계성분', '약효분류코드', '금기내용', '연령기준', '최대투여기간',
       '1일최대용량', '등급', '병용금기DUR성분코드', '병용금기DUR성분명','병용금기복합제', '병용금기관계성분', '병용금기약효분류']]
durr.columns = ['DUR_code', 'drug', 'k_drug', 'comp', 'relation', 'class', 'adr', 'age', 'period', 'dosage', 'grade', 'DUR_code2', 'drug2', 'comp2', 'relation2', 'class2']

In [ ]:
durr.head(2)

  DUR_code  ...             class2
0  D001171  ...        [01130]항전간제
1  D001171  ...  [01190]기타의 중추신경용약

[2 rows x 16 columns]

In [ ]:
rxi_cp= rxi.copy()
rxi.dropna(axis = 0, inplace=True)
rxi['drug'] = rxi['name'].apply(lambda x : x.split(' ')[0])
rxi['drug'] = rxi['drug'].str.lower()
rxi

              ndc11  ...           drug
0     00093-0311-01  ...     loperamide
1     00093-3165-01  ...    minocycline
2     00093-0810-01  ...  nortriptyline
3     00093-0811-01  ...  nortriptyline
4     00093-0812-01  ...  nortriptyline
...             ...  ...            ...
4387  16714-0442-01  ...      enalapril
4388  31722-0267-90  ...      quinapril
4389  00574-0145-60  ...       trospium
4390  64720-0126-10  ...     metaxalone
4391  23155-0055-19  ...    naratriptan

[4332 rows x 19 columns]

In [ ]:
eldery_cp = eldery.copy()
eldery = eldery[eldery['drug'].isin(eldery['drug'].dropna(axis = 0))]
eldery['drug'] = eldery['drug'].apply(lambda x : x.rstrip('*'))
eldery['drug'] = eldery['drug'].str.lower()
eldery

         organ          class             drug drug_korean page  Unnamed: 6
index
1         근골격계        해열진통소염제      aceclofenac     아세클로페낙*   56         NaN
2         근골격계        해열진통소염제       acemetacin      아세메타신*   57         NaN
3         근골격계        해열진통소염제    acetaminophen     아세트아미노펜   58         NaN
4         근골격계        해열진통소염제          aspirin       아스피린*   59         NaN
5         근골격계        해열진통소염제    buprenorphine     부프레노르핀*   60         NaN
...        ...            ...              ...         ...  ...         ...
207    피부/호흡기계         항히스타민제       clemastine      클레마스틴*  311         NaN
208    피부/호흡기계         항히스타민제        oxatomide     옥사토마이드*  312         NaN
209    피부/호흡기계         항히스타민제  piprinhydrinate  피프린히드리네이트*  313         NaN
210    피부/호흡기계  정신신경용제/항히스타민제      hydroxyzine       히드록시진  314         NaN
211    피부/호흡기계    아편알칼로이드계 제제          codeine         코데인  315         NaN

[217 rows x 6 columns]

In [ ]:
top.columns = ['drug', 'total', 'total_pt', 'change']
drug_101.columns = ['name']
preg.columns = ['drug', 'formulation', 'grade', 'organ']
kid.columns = ['drug', 'ix', 'class', 'page']
preg_ph.columns = ['drug', 'grade', 'note', 'comment']
kid_ph.columns = ['drug', 'age', 'formulation', 'comment']
com_ph.columns = ['drug','drug2','adr','note']
period_ph.columns = ['drug','formulation','dosage','period', 'note']
dup_ph.columns = ['class','group','subtype','drug', 'note']
eldery_ph.columns = ['drug','formulation','comment']
dg_ph.columns = ['drug','formulation','dosage', 'note']

In [ ]:
dg_ph

                          drug      formulation                dosage note
연번
1                   Gabapentin          정제, 캡슐제                3600mg  NaN
2                  Galantamine    서방형캡슐제, 서방형정제                  24mg  NaN
3                  Guaifenesin              시럽제                2400mg  NaN
4            Potassium citrate            서방형정제              10,800mg  NaN
5    Granisetron hydrochloride  정제, 구강붕해정제, 주사제     Granisetron으로 9mg  NaN
..                         ...              ...                   ...  ...
354                Phentermine  정제, 캡슐제, 서방형캡슐제                37.5mg  NaN
355                 Vigabatrin               정제                    3g  NaN
356   Sucroferric oxyhydroxide               정제                3000mg  NaN
357     Acetaminophen/Pamabrom               정제          3000mg/150mg  복합제
358     Tipiracil/Trifluridine               정제  Trifluridine으로 160mg  복합제

[358 rows x 4 columns]

In [ ]:
com_ph.columns = ['drug','drug2','adr','note', 'combination',	'prohibition']

ValueError: ignored

In [ ]:
# durr['cate'] = 'dur'
# rxi['cate'] = 'rxi'
# top['cate'] = 'top'
# drug_101['cate'] = 'drug101'

# com_ph['cate'] = 'combination_ph'
# period_ph['cate'] = 'period_ph'
# dup_ph['cate'] = 'duplicaton_ph'
# dg_ph['cate'] = 'dosage_ph'

# com_ph['cate'] = 'combination_ph'
# period_ph['cate'] = 'period_ph'
# dup_ph['cate'] = 'duplicaton_ph'
# dg_ph['cate'] = 'dosage_ph'

# # liver['cate'] = 'liver'
# # kidney['cate'] = 'kidney'

# # preg['cate'] = 'pregnant'
# # kid['cate'] = 'kid'
# # eldery['cate'] = 'eldery'

# # preg_ph['cate'] = 'pregnant_ph'
# # kid_ph['cate'] = 'kid_ph'
# # eldery_ph['cate'] = 'eldery_ph'


# liver['patient'] = 'liver'
# kidney['patient'] = 'kidney'

# preg['patient'] = 'pregnant'
# kid['patient'] = 'kid'
# eldery['patient'] = 'eldery'

# preg_ph['patient'] = 'pregnant_ph'
# kid_ph['patient'] = 'kid_ph'
# eldery_ph['patient'] = 'eldery_ph'

# # preg_ph['patient'] = 'pregnant'
# # kid_ph['patient'] = 'kid'
# # eldery_ph['patient'] = 'eldery'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
# durr['cate'] = 'dur'
# rxi['cate'] = 'rxi'
# top['cate'] = 'top'
# drug_101['cate'] = 'drug101'

# com_ph['cate'] = 'combination_ph'
# period_ph['cate'] = 'period_ph'
# dup_ph['cate'] = 'duplicaton_ph'
# dg_ph['cate'] = 'dosage_ph'

# com_ph['prohibition'] = 'combination'
# period_ph['caution'] = 'period'
# dup_ph['caution'] = 'duplicaton'
# dg_ph['caution'] = 'dosage'

# # liver['cate'] = 'liver'
# # kidney['cate'] = 'kidney'

# # preg['cate'] = 'pregnant'
# # kid['cate'] = 'kid'
# # eldery['cate'] = 'eldery'

# # preg_ph['cate'] = 'pregnant_ph'
# # kid_ph['cate'] = 'kid_ph'
# # eldery_ph['cate'] = 'eldery_ph'


# liver['patient'] = 'liver'
# kidney['patient'] = 'kidney'

# preg['patient'] = 'pregnant'
# kid['patient'] = 'kid'
# eldery['patient'] = 'eldery'

# preg_ph['prohibition'] = 'pregnant'
# kid_ph['prohibition'] = 'kid'
# eldery_ph['prohibition'] = 'eldery'

# # preg_ph['patient'] = 'pregnant'
# # kid_ph['patient'] = 'kid'
# # eldery_ph['patient'] = 'eldery'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
# durr['cate'] = 'dur'
# rxi['cate'] = 'rxi'
# top['cate'] = 'top'
# drug_101['cate'] = 'drug101'

# com_ph['cate'] = 'combination_ph'
# period_ph['cate'] = 'period_ph'
# dup_ph['cate'] = 'duplicaton_ph'
# dg_ph['cate'] = 'dosage_ph'

# # com_ph['prohibition'] = 'combination'
# # period_ph['caution'] = 'period'
# # dup_ph['caution'] = 'duplicaton'
# # dg_ph['caution'] = 'dosage'

# com_ph['alarm'] = 'prohibition'
# durr['alarm'] = 'prohibition'

# period_ph['alarm'] = 'caution'
# dup_ph['alarm'] = 'caution'
# dg_ph['alarm'] = 'caution'

# # liver['cate'] = 'liver'
# # kidney['cate'] = 'kidney'

# # preg['cate'] = 'pregnant'
# # kid['cate'] = 'kid'
# # eldery['cate'] = 'eldery'

# # preg_ph['cate'] = 'pregnant_ph'
# # kid_ph['cate'] = 'kid_ph'
# # eldery_ph['cate'] = 'eldery_ph'


# liver['patient'] = 'liver'
# kidney['patient'] = 'kidney'

# liver['alarm'] = 'caution'
# kidney['alarm'] = 'caution'

# preg['patient'] = 'pregnant'
# kid['patient'] = 'kid'
# eldery['patient'] = 'eldery'

# preg['alarm'] = 'caution'
# kid['alarm'] = 'caution'
# eldery['alarm'] = 'caution'

# preg_ph['patient'] = 'pregnant'
# kid_ph['patient'] = 'kid'
# eldery_ph['patient'] = 'eldery'

# preg_ph['alarm'] = 'prohibition'
# kid_ph['alarm'] = 'prohibition'
# eldery_ph['alarm'] = 'prohibition'

# # preg_ph['patient'] = 'pregnant'
# # kid_ph['patient'] = 'kid'
# # eldery_ph['patient'] = 'eldery'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
#durr[''] = 1
rxi['rxi'] = 1
top['top'] = 1
#drug_101['cate'] = 'drug101'

durr['combination'] = 1
com_ph['combination'] = 1
period_ph['period'] = 1
dup_ph['duplication'] = 1
dg_ph['dosage'] = 1

# com_ph['alarm'] = 'prohibition'
# durr['alarm'] = 'prohibition'

# period_ph['alarm'] = 'caution'
# dup_ph['alarm'] = 'caution'
# dg_ph['alarm'] = 'caution'

com_ph['prohibition'] = 1
durr['prohibition'] = 1

period_ph['caution'] = 1
dup_ph['caution'] = 1
dg_ph['caution'] = 1


liver['liver'] = 1
kidney['kidney'] = 1

liver['caution'] = 1
kidney['caution'] = 1


# liver['alarm'] = 'caution'
# kidney['alarm'] = 'caution'

preg['pregnant'] = 1
kid['kid'] = 1
eldery['eldery'] = 1

preg_ph['pregnant'] = 1
kid_ph['kid'] = 1
eldery_ph['eldery'] = 1

# preg['alarm'] = 'caution'
# kid['alarm'] = 'caution'
# eldery['alarm'] = 'caution'

preg['caution'] = 1
kid['caution'] = 1
eldery['caution'] = 1

# preg_ph['patient'] = 'pregnant'
# kid_ph['patient'] = 'kid'
# eldery_ph['patient'] = 'eldery'

preg_ph['prohibition'] = 1
kid_ph['prohibition'] = 1
eldery_ph['prohibition'] = 1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
dg_ph['drug'] = dg_ph['drug'].str.lower()
dup_ph['drug'] = dup_ph['drug'].str.lower()
period_ph['drug'] = period_ph['drug'].str.lower()
com_ph['drug'] = com_ph['drug'].str.lower()
com_ph['drug2'] = com_ph['drug2'].str.lower()
durr['drug'] = durr['drug'].str.lower()
liver['drug'] = liver['drug'].str.lower()
kidney['drug'] = kidney['drug'].str.lower()

preg['drug'] = preg['drug'].str.lower()
kid['drug'] = kid['drug'].str.lower()
eldery['drug'] = eldery['drug'].str.lower()

preg_ph['drug'] = preg_ph['drug'].str.lower()
kid_ph['drug'] = kid_ph['drug'].str.lower()
eldery_ph['drug'] = eldery_ph['drug'].str.lower()

durr['drug'] = durr['drug'].str.lower()
durr['drug2'] = durr['drug2'].str.lower()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
def cleantt(readData):
 
    #텍스트에 포함되어 있는 특수 문자 제거
 
    text = re.sub(r'\([^)]*\)', '', readData)
 
    return text

In [ ]:
top['drug'] = top['drug'].str.lower().apply(lambda x : cleantt(x))

In [ ]:
dg_ph['drug'] = dg_ph['drug'].str.lower().apply(lambda x : cleantt(x))
dup_ph['drug'] = dup_ph['drug'].str.lower().apply(lambda x : cleantt(x))
period_ph['drug'] = period_ph['drug'].str.lower().apply(lambda x : cleantt(x))
com_ph['drug'] = com_ph['drug'].str.lower().apply(lambda x : cleantt(x))
com_ph['drug2'] = com_ph['drug2'].str.lower().apply(lambda x : cleantt(x))
durr['drug'] = durr['drug'].str.lower().apply(lambda x : cleantt(x))
liver['drug'] = liver['drug'].str.lower().apply(lambda x : cleantt(x))
kidney['drug'] = kidney['drug'].str.lower().apply(lambda x : cleantt(x))

preg['drug'] = preg['drug'].str.lower().apply(lambda x : cleantt(x))
kid['drug'] = kid['drug'].str.lower().apply(lambda x : cleantt(x))
eldery['drug'] = eldery['drug'].str.lower().apply(lambda x : cleantt(x))

preg_ph['drug'] = preg_ph['drug'].str.lower().apply(lambda x : cleantt(x))
kid_ph['drug'] = kid_ph['drug'].str.lower().apply(lambda x : cleantt(x))
eldery_ph['drug'] = eldery_ph['drug'].str.lower().apply(lambda x : cleantt(x))

durr['drug'] = durr['drug'].str.lower().apply(lambda x : cleantt(x))
durr['drug2'] = durr['drug2'].str.lower().apply(lambda x : cleantt(x))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

# Duplication/Dosage/Period

In [ ]:
display(dg_ph.head())
display(dup_ph.tail())
display(period_ph.head())

                         drug      formulation  ...  caution        drug2
연번                                              ...
1                  gabapentin          정제, 캡슐제  ...        1   Gabapentin
2                 galantamine    서방형캡슐제, 서방형정제  ...        1  Galantamine
3                 guaifenesin              시럽제  ...        1  Guaifenesin
4           potassium citrate            서방형정제  ...        1    Potassium
5   granisetron hydrochloride  정제, 구강붕해정제, 주사제  ...        1  Granisetron

[5 rows x 6 columns]

     class  group                    subtype  ... duplication caution    drug2
연번                                            ...
364  당뇨병용제      7  식사 인슐린 (Prandial insulin)  ...           1       1    Human
365  당뇨병용제      8     기저 인슐린 (Basal insulin)  ...           1       1    Human
366  당뇨병용제      8     기저 인슐린 (Basal insulin)  ...           1       1  Insulin
367  당뇨병용제      8     기저 인슐린 (Basal insulin)  ...           1       1  Insulin
368  당뇨병용제      8     기저 인슐린 (Basal insulin)  ...           1       1  Insulin

[5 rows x 8 columns]

                         drug formulation  ... caution             drug2
연번                                         ...
1                   triazolam          정제  ...       1         Triazolam
2                    zolpidem    정제, 속붕정제  ...       1          Zolpidem
3            thiocolchicoside         캡슐제  ...       1  Thiocolchicoside
4            thiocolchicoside         주사제  ...       1  Thiocolchicoside
5   thiocolchicoside / aescin          정제  ...       1  Thiocolchicoside

[5 rows x 7 columns]

In [ ]:
dup_ph['drug2'] = dup_ph['drug'].apply(lambda x : x.split(' ')[0].rstrip())
dg_ph['drug2'] = dg_ph['drug'].apply(lambda x : x.split(' ')[0].rstrip())
period_ph['drug2'] = period_ph['drug'].apply(lambda x : x.split(' ')[0].rstrip())

In [ ]:
# dg_ph2 = dg_ph[['drug2', 'dosage', 'alarm', 'cate', 'caution']]
# dup_ph2 = dup_ph[['drug2', 'class', 'subtype', 'alarm', 'cate', 'caution']]
# period_ph2 = period_ph[['drug2', 'dosage', 'period', 'alarm', 'cate', 'caution']]

In [ ]:
dup_ph[['drug', 'class', 'subtype', 'group', 'duplication', 'caution', 'drug2', 'note']].to_csv("./drug_dupliation.csv", index=False)

In [ ]:
dg_ph2 = dg_ph[['drug2', 'dosage']]
dup_ph2 = dup_ph[['drug2', 'class', 'subtype', 'duplication']]
period_ph2 = period_ph[['drug2', 'period']]

In [ ]:
dg_ph2 = dg_ph[['drug', 'dosage']]
dup_ph2 = dup_ph[['drug', 'class', 'subtype', 'group', 'duplication']]
period_ph2 = period_ph[['drug', 'period']]

In [ ]:
# pd.concat([dup_ph2, dg_ph2], join='outer', axis=0)

                      drug2    class  ... duplication  dosage
연번                                    ...
1               Aceclofenac  해열진통소염제  ...         1.0     NaN
2                Acemetacin  해열진통소염제  ...         1.0     NaN
3                   Aspirin  해열진통소염제  ...         1.0     NaN
4                   Amfenac  해열진통소염제  ...         1.0     NaN
5                 Celecoxib  해열진통소염제  ...         1.0     NaN
..                      ...      ...  ...         ...     ...
354             Phentermine      NaN  ...         NaN     1.0
355              Vigabatrin      NaN  ...         NaN     1.0
356             Sucroferric      NaN  ...         NaN     1.0
357  Acetaminophen/Pamabrom      NaN  ...         NaN     1.0
358  Tipiracil/Trifluridine      NaN  ...         NaN     1.0

[726 rows x 5 columns]

In [ ]:
dup_dg = pd.merge(dup_ph2, dg_ph2, how='outer', on = 'drug')
dup_dg_pr = pd.merge(dup_dg, period_ph2, how='outer', on = 'drug')
dup_dg_pr.tail(30)

                                        drug class  ... dosage  period
687             pseudoephedrine / cetirizine   NaN  ...    NaN     1.0
688                              granisetron   NaN  ...    NaN     1.0
689                               ramosetron   NaN  ...    NaN     1.0
690                           metoclopramide   NaN  ...    NaN     1.0
691                            oxymetazoline   NaN  ...    NaN     1.0
692                                 propofol   NaN  ...    NaN     1.0
693                            anidulafungin   NaN  ...    NaN     1.0
694                                bisacodyl   NaN  ...    NaN     1.0
695                               ciclopirox   NaN  ...    NaN     1.0
696                        echinacea extract   NaN  ...    NaN     1.0
697                                imiquimod   NaN  ...    NaN     1.0
698                           menotrophin hp   NaN  ...    NaN     1.0
699                     pelargonium sidoides   NaN  ...    NaN     1.0
700                          phenazopyridine   NaN  ...    NaN     1.0
701                           xylometazoline   NaN  ...    NaN     1.0
702         xylometazoline/ chlorpheniramine   NaN  ...    NaN     1.0
703                              loteprednol   NaN  ...    NaN     1.0
704                               clobetasol   NaN  ...    NaN     1.0
705                               clobetasol   NaN  ...    NaN     1.0
706             clobetasol/neomycin/nystatin   NaN  ...    NaN     1.0
707                              clobetasone   NaN  ...    NaN     1.0
708                                 desonide   NaN  ...    NaN     1.0
709                           desoximetasone   NaN  ...    NaN     1.0
710                            prednicarbate   NaN  ...    NaN     1.0
711              fusidic acid/hydrocortisone   NaN  ...    NaN     1.0
712         pseudoephedrine / levocetirizine   NaN  ...    NaN     1.0
713          kaolin/berberine tannate/pectin   NaN  ...    NaN     1.0
714  octenidine hydrochloride/phenoxyethanol   NaN  ...    NaN     1.0
715                               vonoprazan   NaN  ...    NaN     1.0
716                               remdesivir   NaN  ...    NaN     1.0

[30 rows x 7 columns]

In [ ]:
len(dup_dg_pr.drug.duplicated())

717

In [ ]:
dup_dg_pr.to_csv('./dup_dg_pr.csv')

In [ ]:
dup_dg_pr[['drug', 'dosage', 'period']].to_csv('./dg_pr.csv')

# Drug class

In [ ]:
drug_class_d1 = dup_dg_pr[['drug', 'class', 'subtype', 'group']]

In [ ]:
drug_class_m4 = pd.read_csv('./drug_class_m4.csv', index_col = 0)
drug_class_m5 = drug_class_m4.groupby('drug').head(1)
drug_class_m5.shape, drug_class_d1.shape

((1456, 3), (717, 4))

In [ ]:
#drug_class_m4 = pd.read_csv('./drug_class_m4.csv', index_col = 0)
drug_class_m5 = drug_class_m4.groupby('drug').head(1)
drug_class_m5.shape, drug_class_d1.shape

((869, 2), (717, 4))

In [ ]:
drug_class_m4.groupby('drug').head(1).to_csv('./drug_class_m5.csv')

In [ ]:
drug_class_m6 = pd.merge(drug_class_m5, drug_class_d1, on = ['drug', 'class'], how = 'outer')

In [ ]:
drug_class_m6.to_csv('./drug_class_m6.csv', index = False)

In [ ]:
groupby first
https://stackoverflow.com/questions/20067636/pandas-dataframe-get-first-row-of-each-group
https://learnsql.com/cookbook/how-to-select-the-first-row-in-each-group-by-group/

In [ ]:
len(dup_ph.drug2.unique()), len(dup_ph.drug.unique())

(360, 368)

In [ ]:
len(set(preg.성분명).intersection(set(preg_ph.성분명))) #317 + 1073 /231
len(set(top.drug).intersection(set(preg_ph.성분명))) #124
len(set(eldery_ph.성분명).union(set(eldery.drug2))) # / 68 , 245
len(set(top.drug).union(set(eldery_ph.성분명))) # 63
len(set(top.drug).intersection(set(dup_ph.성분명))) # 47
len(set(top.drug).intersection(set(kidney.drug))) # 73
#len(set(top.drug).intersection(set(liver.drug))) # 70
len(set(top.drug).intersection(set(com_ph.comp1))) #8
len(set(top.drug).intersection(set(com_ph.comp2))) # 14

14

In [ ]:
# len(set(preg.성분명).intersection(set(preg_ph.성분명))) #317 + 1073 /231
len(set(rxi.drug).intersection(set(preg_ph.성분명))) #190
# len(set(eldery_ph.성분명).union(set(eldery.drug2))) # / 68 , 245
#len(set(rxi.drug).intersection(set(eldery_ph.성분명))) # 37
#len(set(rxi.drug).intersection(set(dup_ph.성분명))) # 70
#len(set(rxi.drug).intersection(set(kidney.drug))) # 100
#len(set(rxi.drug).intersection(set(liver.drug))) # 102
#len(set(rxi.drug).intersection(set(com_ph.comp1))) #36
#len(set(rxi.drug).intersection(set(com_ph.comp2))) # 53

190

In [ ]:
len(set(top.drug).intersection(set(rxi.drug)).intersection(set(preg_ph.성분명))) #72
#len(set(top.drug).intersection(set(rxi.drug)).intersection(set(eldery_ph.성분명))) # 11
#len(set(top.drug).intersection(set(rxi.drug)).intersection(set(dup_ph.성분명))) # 23
#len(set(top.drug).intersection(set(rxi.drug)).intersection(set(kidney.drug))) # 51
#len(set(top.drug).intersection(set(rxi.drug)).intersection(set(liver.drug))) # 44
#len(set(top.drug).intersection(set(rxi.drug)).intersection(set(com_ph.comp1))) #7
#len(set(top.drug).intersection(set(rxi.drug)).intersection(set(com_ph.comp2))) # 10

72

# Patient_Table

In [ ]:
display(preg.head())
display(preg_ph.head())

                                         drug  ... organ
금기\n연번                                         ...
1       progesterone, micronized progesterone  ...  내분비계
2                                 aceclofenac  ...  근골격계
3                                  acemetacin  ...  근골격계
4                                   acitretin  ...  근골격계
5                                   alacepril  ...  순환기계

[5 rows x 4 columns]

                               drug  ...                                            comment
3                                    ...
1        (micronized) progesterone   ...                                    임부에 대한 안전성 미확립.
2  3'-deoxy-3'-fluorothymidine(18f)  ...                                    임부에 대한 안전성 미확립.
3                          abacavir  ...  임부에 대한 안전성 미확립.\n동물실험에서 태반이행 보고. 랫드에서 태자 체중감소,...
4                         abatacept  ...   임부에 대한 안전성 미확립.\n동물실험에서 면역기능변형(갑상선과 췌장의 감염 등)보고.
5                       abiraterone  ...    임부에 대한 안전성 미확립.\n모체의 호르몬 농도변화로 인한 태아발달에 위해 가능성.

[5 rows x 4 columns]

In [ ]:
preg_class = pd.concat([preg[['drug', 'organ', 'grade']], preg_ph[['drug', 'grade']]], join='outer', axis=0 )

In [ ]:
preg_class = pd.concat([preg[['drug', 'organ']], preg_ph[['drug']]], join='outer', axis=0 )

In [ ]:
preg_class

                                                   drug organ
1                 progesterone, micronized progesterone  내분비계
2                                           aceclofenac  근골격계
3                                            acemetacin  근골격계
4                                             acitretin  근골격계
5                                             alacepril  순환기계
...                                                 ...   ...
1073                           tipiracil + trifluridine   NaN
1074                                           olaparib   NaN
1075                                         ribociclib   NaN
1076  bictegravir + emtricitabine + tenofovir alafen...   NaN
1077                                 baloxavir marboxil   NaN

[1387 rows x 2 columns]

In [ ]:
preg_m = pd.merge(preg[['drug', 'caution', 'grade']], preg_ph[['drug', 'prohibition', 'comment', 'grade']], on=['drug', 'grade'], how = 'outer' )
preg_m['pregnant'] = 1

In [ ]:
preg_m

                                                   drug  ...  pregnant
0                 progesterone, micronized progesterone  ...         1
1                                           aceclofenac  ...         1
2                                            acemetacin  ...         1
3                                             acitretin  ...         1
4                                             alacepril  ...         1
...                                                 ...  ...       ...
1162                           tipiracil + trifluridine  ...         1
1163                                           olaparib  ...         1
1164                                         ribociclib  ...         1
1165  bictegravir + emtricitabine + tenofovir alafen...  ...         1
1166                                 baloxavir marboxil  ...         1

[1167 rows x 6 columns]

In [ ]:
display(kid_ph.head())
display(kid.head())

              drug     age  ... kid prohibition
연번                          ...
1         acarbose  18세 이하  ...   1           1
2   acetaminophen   12세 미만  ...   1           1
3      albendazole   2세 미만  ...   1           1
4    alclometasone   1세 이하  ...   1           1
5        aloxiprin  14세 이하  ...   1           1

[5 rows x 6 columns]

                             drug   ix     class page  kid  caution
0                   Acetaminophen   47   해열진통소염제  104    1        1
1                  Acetylcysteine   95  호흡기계  약물  169    1        1
2                       Acyclovir   44    항바이러스제   97    1        1
3  Albumin,  Human  Normal  Serum  149       영양제  246    1        1
4                    Alfacalcidol  150       영양제  247    1        1

In [ ]:
kid_m = pd.merge(kid[['drug', 'caution']], kid_ph[['drug', 'prohibition', 'comment']], on='drug', how = 'outer' )
kid_m['kid']=1
kid_m

                                                  drug  ...  kid
0                                        acetaminophen  ...    1
1                                       acetylcysteine  ...    1
2                                            acyclovir  ...    1
3                       albumin,  human  normal  serum  ...    1
4                                         alfacalcidol  ...    1
..                                                 ...  ...  ...
397  calcium carbonate + cinnamon oil + diastase-pr...  ...    1
398  calcium carbonate + pulvis cinnamomi corticis ...  ...    1
399                     milk-thistle fruit dry extract  ...    1
400  calcium pantothenate + cyanocobalamin + milk-t...  ...    1
401                           tipiracil + trifluridine  ...    1

[402 rows x 5 columns]

In [ ]:
display(eldery.head())
display(eldery_ph.head())

      organ    class           drug  ... Unnamed: 6 eldery  caution
index                                ...
1      근골격계  해열진통소염제    aceclofenac  ...        NaN      1        1
2      근골격계  해열진통소염제     acemetacin  ...        NaN      1        1
3      근골격계  해열진통소염제  acetaminophen  ...        NaN      1        1
4      근골격계  해열진통소염제        aspirin  ...        NaN      1        1
5      근골격계  해열진통소염제  buprenorphine  ...        NaN      1        1

[5 rows x 8 columns]

             drug formulation  ... eldery  prohibition
연번                             ...
1   nortriptyline          정제  ...      1            1
2       dothiepin         캡슐제  ...      1            1
3        diazepam          정제  ...      1            1
4        diazepam         주사제  ...      1            1
5       mexazolam          정제  ...      1            1

[5 rows x 5 columns]

In [ ]:
eldery_m = pd.merge(eldery[['drug', 'caution']], eldery_ph[['drug', 'prohibition', 'comment']], on='drug', how = 'outer' )
eldery_m['eldery']=1
eldery_m

                     drug  caution  prohibition comment  eldery
0             aceclofenac      1.0          1.0     NaN       1
1              acemetacin      1.0          NaN     NaN       1
2           acetaminophen      1.0          NaN     NaN       1
3                 aspirin      1.0          1.0     NaN       1
4           buprenorphine      1.0          NaN     NaN       1
..                    ...      ...          ...     ...     ...
246          flurbiprofen      NaN          1.0     NaN       1
247  imidazole salicylate      NaN          1.0     NaN       1
248            polmacoxib      NaN          1.0     NaN       1
249           pranoprofen      NaN          1.0     NaN       1
250         proglumetacin      NaN          1.0     NaN       1

[251 rows x 5 columns]

In [ ]:
drug_class = pd.merge(eldery[['drug', 'organ', 'class']], kid[['drug', 'class']], on=['drug', 'class'], how = 'outer' )

In [ ]:
# drug_class = pd.concat([eldery[['drug', 'organ', 'class']], kid[['drug', 'class']]], join = 'outer' )

In [ ]:
drug_class['drug'].str.lower()

0           aceclofenac
1            acemetacin
2         acetaminophen
3               aspirin
4         buprenorphine
             ...
434          vigabatrin
435    warfarin  sodium
436       zinc  acetate
437       zinc  sulfate
438          zonisamide
Name: drug, Length: 439, dtype: object

In [ ]:
drug_class.apply(lambda x : x.str.lower() )

                 drug organ     class
0         aceclofenac  근골격계   해열진통소염제
1          acemetacin  근골격계   해열진통소염제
2       acetaminophen  근골격계   해열진통소염제
3             aspirin  근골격계   해열진통소염제
4       buprenorphine  근골격계   해열진통소염제
..                ...   ...       ...
441        vigabatrin   NaN   신경계  약물
442  warfarin  sodium   NaN  혈액질환  약물
443     zinc  acetate   NaN  소화기계  약물
444     zinc  sulfate   NaN       영양제
445        zonisamide   NaN   신경계  약물

[446 rows x 3 columns]

In [ ]:
drug_class

                 drug organ     class
0         aceclofenac  근골격계   해열진통소염제
1          acemetacin  근골격계   해열진통소염제
2       acetaminophen  근골격계   해열진통소염제
3             aspirin  근골격계   해열진통소염제
4       buprenorphine  근골격계   해열진통소염제
..                ...   ...       ...
434        vigabatrin   NaN   신경계  약물
435  warfarin  sodium   NaN  혈액질환  약물
436     zinc  acetate   NaN  소화기계  약물
437     zinc  sulfate   NaN       영양제
438        zonisamide   NaN   신경계  약물

[439 rows x 3 columns]

In [ ]:
# drug_preg_class = pd.concat([preg_class[['drug', 'organ', 'grade']], drug_class[['drug', 'class']]], join = 'outer' )

In [ ]:
!pwd

/content/drive/Shareddrives/Codepresso_8/Drug_list

In [ ]:
preg_class

                                                   drug organ
1                 progesterone, micronized progesterone  내분비계
2                                           aceclofenac  근골격계
3                                            acemetacin  근골격계
4                                             acitretin  근골격계
5                                             alacepril  순환기계
...                                                 ...   ...
1073                           tipiracil + trifluridine   NaN
1074                                           olaparib   NaN
1075                                         ribociclib   NaN
1076  bictegravir + emtricitabine + tenofovir alafen...   NaN
1077                                 baloxavir marboxil   NaN

[1387 rows x 2 columns]

In [ ]:
drug_class

                 drug organ     class
0         aceclofenac  근골격계   해열진통소염제
1          acemetacin  근골격계   해열진통소염제
2       acetaminophen  근골격계   해열진통소염제
3             aspirin  근골격계   해열진통소염제
4       buprenorphine  근골격계   해열진통소염제
..                ...   ...       ...
434        vigabatrin   NaN   신경계  약물
435  warfarin  sodium   NaN  혈액질환  약물
436     zinc  acetate   NaN  소화기계  약물
437     zinc  sulfate   NaN       영양제
438        zonisamide   NaN   신경계  약물

[439 rows x 3 columns]

In [ ]:
https://snepbnt.tistory.com/378

In [ ]:
drug_preg_class = pd.merge(preg_class[['drug', 'organ']], drug_class[['drug', 'organ', 'class']], on=['drug', 'organ'], how = 'outer'  )

In [ ]:
len(drug_preg_class.drug.unique())

1356

In [ ]:
len(drug_preg_class.drug.unique())

1356

In [ ]:
len(drug_preg_class.drug)

1735

In [ ]:
def cleant2(readData):
  
  text = re.sub(r'\[[^)]*\]', '', readData)
  
  return text

In [ ]:
dur_class_m2

In [ ]:
dur_class_m2.shape, dur_class_m2.dropna().shape

((383, 1), (367, 1))

In [ ]:
dur_class_m2_dropna = dur_class_m2.dropna()

In [ ]:
cleant2(dur_class_m2_dropna['class'][0])

'기타의 화학요법제'

In [ ]:
dur_class_m2['class'] = dur_class_m2['class'].apply(lambda x : cleant2(str(x)))

In [ ]:
dur_class_m2

                    class
drug
abacavir        기타의 화학요법제
abiraterone        항악성종양제
aceclofenac     해열.진통.소염제
acemetacin      해열.진통.소염제
acetazolamide         이뇨제
...                   ...
zalcitabine     기타의 화학요법제
zaltoprofen     해열.진통.소염제
ziprasidone        정신신경용제
zolmitriptan    해열.진통.소염제
zuclopenthixol     정신신경용제

[372 rows x 1 columns]

In [ ]:
drug_preg_class['grade'] = drug_preg_class['grade'].fillna(0)

In [ ]:
drug_class_m4 = pd.merge(drug_preg_class, dur_class_m2, on= ['drug', 'class'], how='outer').groupby('drug').first()

In [ ]:
drug_class_m4  = drug_class_m4.dropna(subset=['organ','class'], how = 'all')

In [ ]:
drug_class_m4

                organ      class
drug
abacavir         None  기타의 화학요법제
abiraterone      None     항악성종양제
aceclofenac      근골격계    해열진통소염제
acemetacin       근골격계    해열진통소염제
acetaminophen    근골격계    해열진통소염제
...               ...        ...
zonisamide      신경정신계    신경계  약물
zotepine        신경정신계      항정신용제
zuclopenthixol   None     정신신경용제
성분명               효능군         분류
영문  성분명          None         분류

[869 rows x 2 columns]

In [ ]:
drug_class_m4.to_csv('./drug_class_m4_dropna.csv')

In [ ]:
drug_preg_class['class'].unique()

array([nan, '해열진통소염제', '부정맥용제', '기타의 소화기관용약', '합성마약', '혈관확장제', '남성호르몬제',
       '난포호르몬 및\n황체호르몬제', '항균제', '호흡기계  약물', '면역기계  약물', '영양제',
       '심혈관계  약물', '신경계  약물', '내분비계  약물', '소화기계  약물', '항진균제', '이뇨제',
       '정신계  약물', '항바이러스제', '근골격계  약물', '골격근이완제', '분류', '골대사제제', '부신호르몬제',
       '비타민A및D제', '최면진정제', '항정신용제', '항우울제', '항전간제', '항파킨슨제', '식욕억제제',
       '항치매제', '각성제', '항불안제', '전신마취제', '혈압강하제/기타의비뇨생식\n기관및항문용약', '강심제',
       '기타의 혈액 및 체액용약', '무기질제제', '난포호르몬 및 황체호르몬제', '당뇨병용제', '뇌하수체호르몬제',
       '항악성종양제/여성호르몬제', '진경제', '진토제', '소화성 궤양용제', '정신신경용제', '하제, 완장제',
       '기타의 비뇨생식기관\n및 항문용약', '기타의 비뇨생식기관 및 항문용약',
       '기타의 비뇨생식기관 및 항문용약, 진경제', '항히스타민제', '정신신경용제/항히스타민제', '아편알칼로이드계 제제',
       '혈액질환  약물', '비뇨기계  약물'], dtype=object)

In [ ]:
dur_class_m2['class'].unique()

array(['기타의 화학요법제', '항악성종양제', '해열.진통.소염제', '이뇨제', '비타민 A 및 D제', '간장질환용제',
       '정신신경용제', '기타의 비뇨생식기관 및 항문용약', '기타의 중추신경용약', '지혈제', '부정맥용제',
       '기타의 순환계용약', '기타의 종양치료제', '안과용제', '국소마취제', 'nan',
       '자격요법제(비특이성면역억제제를 포함)', '주로 그람양성균, 리케치아, 비루스에 작용하는 것', '항결핵제',
       '혈압강하제', '따로 분류되지 않는 대사성 의약품', '진통.진양.수렴.소염제', '0',
       '주로 그람양성, 음성균, 리케치아, 비루스에 작용하는 것',
       '기타의 항생물질제제(복합항생물질제제를 포함)기타의 항생물질제제(복합항생물질제제를 포함)기타의 항생물질제제(복합항생물질제제를 포함)/주로 그람양성, 음성균에 작용하는 것',
       '진해거담제', '비뇨생식기관용제(성병예방제포함)/기타의 항생물질제제(복합항생물질제제를 포함)', '통풍치료제',
       '골격근이완제', '자격요법제(비특이성면역억제제를 포함)자격요법제(비특이성면역억제제를 포함)',
       '기타의 호르몬제(항호르몬제를 포함)', '혈액응고저지제', '피임제', '소화성궤양용제', '자율신경제',
       '혈관확장제', '강심제', '최토제, 진토제', '기타의 소화기관용약', '주로 그람양성, 음성균에 작용하는 것',
       '항히스타민제', '부신호르몬제', '기타의 외피용약', '기타의 호르몬제(항호르몬제를 포함)피임제', '동맥경화용제',
       '기타의 호흡기관용약', '항전간제', '주로 그람양성균에 작용하는 것',
       '기타의 항생물질제제(복합항생물질제제를 포함)', '당뇨병용제', '전신마취제', '항원충제', 'X선조영제',
       '난포호르몬제 및 황체호르몬제', '각성제,흥분제', '기타의 항생물질제제(복합항생물질제제를 포함)항원충제',
       '주로 곰팡이, 원충에 작용하는 것', '최면진정제', '아편알카로이드계 제제', '치질용제', '진경제',
       '이비과용제', '합성마약', '혈액대용제', '하제, 완장제', '비타민 B제(비타민 B1을 제외)',
       '방사성 의약품', '주로 항산성균에 작용하는 것',
       '자격요법제(비특이성면역억제제를 포함)/자격요법제(비특이성면역억제제를 포함)',
       '피부연화제(부식제를 포함)/기타의 종양치료제'], dtype=object)

In [ ]:
drug_preg_class.to_csv('./drug_preg_class.csv', index=False)
drug_class_m4.to_csv('./drug_class_m4.csv', index=False)
#drug_preg_class

# Patient_Table

In [ ]:
preg_kid = pd.merge(preg_m, kid_m, how='outer', on = ['drug', 'caution', 'prohibition', 'comment'] )
preg_kid_eldery = pd.merge(preg_kid, eldery_m, how='outer', on = ['drug', 'caution', 'prohibition', 'comment'] )
preg_kid_eldery_fill = preg_kid_eldery.fillna(0).groupby('drug').sum()
#preg_kid2 = pd.merge([preg_m, kid_m], join='outer', axis = 0 )

In [ ]:
preg_kid_eldery = pd.merge(preg_kid, eldery_m, how='outer', on = ['drug', 'caution', 'prohibition', 'comment'] )
preg_kid_eldery

                                       drug  caution  ... kid  eldery
0     progesterone, micronized progesterone      1.0  ... NaN     NaN
1                               aceclofenac      1.0  ... NaN     NaN
2                                acemetacin      1.0  ... NaN     NaN
3                                 acitretin      1.0  ... NaN     NaN
4                                 alacepril      1.0  ... NaN     NaN
...                                     ...      ...  ...  ..     ...
1782                           flurbiprofen      NaN  ... NaN     1.0
1783                   imidazole salicylate      NaN  ... NaN     1.0
1784                             polmacoxib      NaN  ... NaN     1.0
1785                            pranoprofen      NaN  ... NaN     1.0
1786                          proglumetacin      NaN  ... NaN     1.0

[1787 rows x 8 columns]

In [ ]:
liver['liver']=1
kidney['kidney']=1

In [ ]:
liver_kidney = pd.merge(liver[['drug', 'liver','caution']], kidney[['drug', 'kidney','caution']], how='outer', on = ['drug'])
liver_kidney

                drug  liver  caution_x  kidney  caution_y
0           acarbose      1          1       1          1
1        aceclofenac      1          1       1          1
2      acetaminophen      1          1       1          1
3          acyclovir      1          1       1          1
4    alendronic acid      1          1       1          1
..               ...    ...        ...     ...        ...
219         warfarin      1          1       1          1
220      zaltoprofen      1          1       1          1
221       zofenopril      1          1       1          1
222  zoledronic acid      1          1       1          1
223         zolpidem      1          1       1          1

[224 rows x 5 columns]

In [ ]:
#liver_kidney[['caution_x', 'caution_y']].apply(lambda x : x.sum())
#df.groupby(['col1', 'col2']).agg({'col3':'sum','col4':'sum'})
#liver_kidney[['caution_x', 'caution_y']].agg(sum)
liver_kidney['caution_lk'] = liver_kidney[['caution_x', 'caution_y']].sum(axis=1)

In [ ]:
liver_kidney

                drug  liver  caution_x  kidney  caution_y  caution_lk
0           acarbose      1          1       1          1           2
1        aceclofenac      1          1       1          1           2
2      acetaminophen      1          1       1          1           2
3          acyclovir      1          1       1          1           2
4    alendronic acid      1          1       1          1           2
..               ...    ...        ...     ...        ...         ...
219         warfarin      1          1       1          1           2
220      zaltoprofen      1          1       1          1           2
221       zofenopril      1          1       1          1           2
222  zoledronic acid      1          1       1          1           2
223         zolpidem      1          1       1          1           2

[224 rows x 6 columns]

In [ ]:
patient_m1 = pd.merge(liver_kidney[['drug', 'liver', 'kidney', 'caution_lk']], preg_kid_eldery, on = 'drug', how = 'outer')
patient_m1

                      drug  liver  kidney  ...  pregnant  kid eldery
0                 acarbose    1.0     1.0  ...       1.0  NaN    NaN
1                 acarbose    1.0     1.0  ...       NaN  1.0    NaN
2              aceclofenac    1.0     1.0  ...       1.0  NaN    NaN
3              aceclofenac    1.0     1.0  ...       NaN  NaN    1.0
4            acetaminophen    1.0     1.0  ...       NaN  1.0    1.0
...                    ...    ...     ...  ...       ...  ...    ...
1826             tiquizium    NaN     NaN  ...       NaN  NaN    1.0
1827             flavoxate    NaN     NaN  ...       NaN  NaN    1.0
1828              trospium    NaN     NaN  ...       NaN  NaN    1.0
1829           ethenzamide    NaN     NaN  ...       NaN  NaN    1.0
1830  imidazole salicylate    NaN     NaN  ...       NaN  NaN    1.0

[1831 rows x 11 columns]

In [ ]:
preg_kid_eldery_fill.groupby('drug').sum().to_csv('./preg_kid_eldery_fill.csv')

In [ ]:
patient_m1_fill = patient_m1.fillna('0')
patient_m1_fill

                      drug liver kidney  ... pregnant kid eldery
0                 acarbose     1      1  ...        1   0      0
1                 acarbose     1      1  ...        0   1      0
2              aceclofenac     1      1  ...        1   0      0
3              aceclofenac     1      1  ...        0   0      1
4            acetaminophen     1      1  ...        0   1      1
...                    ...   ...    ...  ...      ...  ..    ...
1826             tiquizium     0      0  ...        0   0      1
1827             flavoxate     0      0  ...        0   0      1
1828              trospium     0      0  ...        0   0      1
1829           ethenzamide     0      0  ...        0   0      1
1830  imidazole salicylate     0      0  ...        0   0      1

[1831 rows x 11 columns]

In [ ]:
!pwd

/content/drive/Shareddrives/Codepresso_8/Drug_list/final_data

In [ ]:
patient_m1['caution_p'] = patient_m1[['caution_lk', 'caution']].sum(axis=1)
patient_m1.to_csv('/content/drive/Shareddrives/Codepresso_8/Drug_list/patient_m1.csv')

In [ ]:
patient_m2 = patient_m1.drop(['caution_lk', 'caution','comment'], axis=1).groupby('drug').sum()
patient_m2.columns

Index(['liver', 'kidney', 'prohibition', 'pregnant', 'kid', 'eldery',
       'caution_p'],
      dtype='object')

In [ ]:
patient_comment= pd.DataFrame(patient_m1_fill.groupby('drug').apply(lambda group: ', '.join(group['comment'])))
patient_comment.columns

RangeIndex(start=0, stop=1, step=1)

In [ ]:
patient_comment

                                                                             0
drug
 progesterone                                                  임부에 대한 안전성 미확립.
2-deoxy-2-fluoro-d-glucose                                 임신 중 투여에 대한 안전성 미확립
3'-deoxy-3'-fluorothymidine                                    임부에 대한 안전성 미확립.
3-iodobenzylguanidine        방사성 요오드 의약품은 태반을 통과하여 태아 갑상선 기능을 영구적으로 손상시킬 수 ...
5-hydroxytryptophan                                                          -
...                                                                        ...
zotepine                                             동물실험에서 신생자의 사망률 증가 보고., 0
zuclopenthixol               임부에 대한 안전성 미확립.\n임신말기나 분만중 복용시 신생아에서 기면, 진전, 과...
성분명                                                           0, 0, 0, 0, 0, 0
약독황열생바이러스백신                                                 임부에 대한 안전성 미확립., ㅡ
영문  성분명                                                                      0

[1487 rows x 1 columns]

In [ ]:
patient_comment= patient_m1_fill.groupby('drug').apply(lambda group: ', '.join(group['comment']))
#patient_comment.columns = 'comment'
patient_comment

drug
 progesterone                                                    임부에 대한 안전성 미확립.
2-deoxy-2-fluoro-d-glucose                                   임신 중 투여에 대한 안전성 미확립
3'-deoxy-3'-fluorothymidine                                      임부에 대한 안전성 미확립.
3-iodobenzylguanidine          방사성 요오드 의약품은 태반을 통과하여 태아 갑상선 기능을 영구적으로 손상시킬 수 ...
5-hydroxytryptophan                                                            -
                                                     ...
zotepine                                               동물실험에서 신생자의 사망률 증가 보고., 0
zuclopenthixol                 임부에 대한 안전성 미확립.\n임신말기나 분만중 복용시 신생아에서 기면, 진전, 과...
성분명                                                             0, 0, 0, 0, 0, 0
약독황열생바이러스백신                                                   임부에 대한 안전성 미확립., ㅡ
영문  성분명                                                                        0
Length: 1487, dtype: object

In [ ]:
patient_comment.columns

'comment'

In [ ]:
patient_m3 = pd.merge(patient_m2, patient_comment, on = 'drug', how='left')
patient_m3
#patient_m3.to_csv('./patient_m3.csv')

                             liver  ...                                                  0
drug                                ...
 progesterone                  0.0  ...                                    임부에 대한 안전성 미확립.
2-deoxy-2-fluoro-d-glucose     0.0  ...                                임신 중 투여에 대한 안전성 미확립
3'-deoxy-3'-fluorothymidine    0.0  ...                                    임부에 대한 안전성 미확립.
3-iodobenzylguanidine          0.0  ...  방사성 요오드 의약품은 태반을 통과하여 태아 갑상선 기능을 영구적으로 손상시킬 수 ...
5-hydroxytryptophan            0.0  ...                                                  -
...                            ...  ...                                                ...
zotepine                       0.0  ...                          동물실험에서 신생자의 사망률 증가 보고., 0
zuclopenthixol                 0.0  ...  임부에 대한 안전성 미확립.\n임신말기나 분만중 복용시 신생아에서 기면, 진전, 과...
성분명                            0.0  ...                                   0, 0, 0, 0, 0, 0
약독황열생바이러스백신                    0.0  ...                                 임부에 대한 안전성 미확립., ㅡ
영문  성분명                        0.0  ...                                                  0

[1487 rows x 8 columns]

In [ ]:
patient_m1_fill.groupby('drug').sum()

                              liver  ...                                            comment
drug                                 ...
 progesterone                     0  ...                                    임부에 대한 안전성 미확립.
2-deoxy-2-fluoro-d-glucose        0  ...                                임신 중 투여에 대한 안전성 미확립
3'-deoxy-3'-fluorothymidine       0  ...                                    임부에 대한 안전성 미확립.
3-iodobenzylguanidine            00  ...  방사성 요오드 의약품은 태반을 통과하여 태아 갑상선 기능을 영구적으로 손상시킬 수 ...
5-hydroxytryptophan               0  ...                                                  -
...                             ...  ...                                                ...
zotepine                         00  ...                            동물실험에서 신생자의 사망률 증가 보고.0
zuclopenthixol                    0  ...  임부에 대한 안전성 미확립.\n임신말기나 분만중 복용시 신생아에서 기면, 진전, 과...
성분명                          000000  ...                                             000000
약독황열생바이러스백신                      00  ...                                   임부에 대한 안전성 미확립.ㅡ
영문  성분명                           0  ...                                                  0

[1487 rows x 4 columns]

In [ ]:
len(preg_kid.drug.unique()), len(preg_kid.drug),len(preg_kid_eldery.drug.unique()),  len(preg_kid_eldery.drug)

(1389, 1549, 1447, 1776)

In [ ]:
preg_kid_eldery[preg_kid_eldery.duplicated()]

            drug  caution  prohibition  ... pregnant  kid  eldery
1428  ketoprofen      NaN          1.0  ...      NaN  1.0     NaN
1602     성분명(영문)      1.0          NaN  ...      NaN  NaN     1.0
1603     성분명(영문)      1.0          NaN  ...      NaN  NaN     1.0
1604     성분명(영문)      1.0          NaN  ...      NaN  NaN     1.0
1605     성분명(영문)      1.0          NaN  ...      NaN  NaN     1.0
1606     성분명(영문)      1.0          NaN  ...      NaN  NaN     1.0
1620    diazepam      1.0          1.0  ...      NaN  NaN     1.0

[7 rows x 7 columns]

In [ ]:
preg_kid_eldery[preg_kid_eldery.duplicated(subset=None, keep='first')]

            drug  caution  prohibition  ... pregnant  kid  eldery
1430  ketoprofen      NaN          1.0  ...      NaN  1.0     NaN
1618     성분명(영문)      1.0          NaN  ...      NaN  NaN     1.0
1619     성분명(영문)      1.0          NaN  ...      NaN  NaN     1.0
1620     성분명(영문)      1.0          NaN  ...      NaN  NaN     1.0
1621     성분명(영문)      1.0          NaN  ...      NaN  NaN     1.0
1622     성분명(영문)      1.0          NaN  ...      NaN  NaN     1.0
1636    Diazepam      1.0          1.0  ...      NaN  NaN     1.0

[7 rows x 7 columns]

In [ ]:
#pregnant
len(set(preg_ph.drug).intersection(set(preg.drug))), len(set(preg_ph.drug).union(set(preg.drug))), len(set(preg_ph.drug)), len(set(preg.drug))

(235, 1152, 1073, 314)

In [ ]:
#kids
len(set(kid_ph.drug).intersection(set(kid.drug))), len(set(kid_ph.drug).union(set(kid.drug))), len(set(kid_ph.drug)), len(set(kid.drug))

(0, 415, 186, 229)

In [ ]:
#eldery
len(set(eldery_ph.drug).intersection(set(eldery.drug))), len(set(eldery_ph.drug).union(set(eldery.drug))), len(set(eldery_ph.drug)), len(set(eldery.drug))

(68, 245, 101, 212)

In [ ]:
len(set(preg_ph.drug).union(set(eldery_ph.성분명)).union(set(dup_ph.성분명)).union(set(kidney.drug)).union(set(liver.drug)).union(set(com_ph.comp1)).union(set(com_ph.comp2)))

1877

In [ ]:
union_sp = set(preg_ph.성분명).union(set(eldery_ph.성분명)).union(set(dup_ph.성분명)).union(set(kidney.drug)).union(set(liver.drug)).union(set(com_ph.comp1)).union(set(com_ph.comp2))

In [ ]:
union_sp0 = set(preg_ph.drug).union(set(eldery_ph.drug)).union(set(dup_ph.drug)).union(set(durr.drug)).union(set(kidney.drug)).union(set(liver.drug)).union(set(com_ph.comp1)).union(set(com_ph.comp2))

In [ ]:
union_sp = set(preg.drug).union(set(eldery.drug)).union(set(kid.drug)).union(set(durr.drug)).union(set(durr.drug2)).union(set(preg_ph.drug)).union(set(eldery_ph.drug)).union(set(kid_ph.drug)).union(set(dup_ph.drug)).union(set(kidney.drug)).union(set(liver.drug)).union(set(com_ph.comp1)).union(set(com_ph.comp2))

# Target list

In [ ]:
top.head(30)

                          drug        total    total_pt change  top
Rank
1                 atorvastatin  112474023.0  23393083.0      1    1
2                levothyroxine  105773990.0  19448097.0      1    1
3                   lisinopril   97608879.0  19941170.0      2    1
4      metformin hydrochloride   83762981.0  16865776.0      0    1
5                   amlodipine   75811947.0  15851641.0      0    1
6                   metoprolol   71581961.0  14583646.0      0    1
7                    albuterol   60526457.0  19211178.0      3    1
8                   omeprazole   58364556.0  13410605.0      1    1
9           losartan potassium   50479750.0  11160547.0      0    1
10                 simvastatin   48007043.0  10407988.0      2    1
11                  gabapentin   45586654.0   9289873.0      0    1
12               acetaminophen   42073176.0  12268763.0      1    1
13         hydrochlorothiazide   40575075.0   8869933.0      1    1
14    sertraline hydrochloride   38383042.0   7529389.0      0    1
15                 montelukast   35222630.0   7017347.0      1    1
16                 fluticasone   34253764.0  10344619.0      1    1
17                 amoxicillin   31371675.0  21697269.0      1    1
18                  furosemide   29857945.0   6330557.0      1    1
19         pantoprazole sodium   28958134.0   6531330.0      0    1
20               acetaminophen   27907360.0   9379461.0      5    1
21                  prednisone   27057494.0  11300598.0      1    1
22        escitalopram oxalate   25978773.0   5544406.0      2    1
23    fluoxetine hydrochloride   25619277.0   4752127.0      8    1
24           dextroamphetamine   25331775.0   3705324.0      3    1
25      tramadol hydrochloride   24952328.0   6952833.0      7    1
26            insulin glargine   24911721.0   4331519.0      7    1
27                   bupropion   24488843.0   5046780.0      4    1
28                   ibuprofen   24453501.0  11636681.0      0    1
29                rosuvastatin   24138061.0   5257942.0     10    1
30          pravastatin sodium   24022031.0   5420488.0      6    1

In [ ]:
len(set(top.drug).intersection(set(rxi.drug)))

153

In [ ]:
len(set(top.drug).intersection(set(rxi.drug)))

153

In [ ]:
dup_dg_pr['drug2'] = dup_dg_pr['drug'].apply(lambda x : x.split('/')[0])

In [ ]:
dup_dg_pr.to_csv('./dup_dg_pr.csv')

In [ ]:
patient_m3.reset_index(inplace=True)

In [ ]:
patient_m3.drug

0                     progesterone
1       2-deoxy-2-fluoro-d-glucose
2       3'-deoxy-3'-fluorothymidine
3            3-iodobenzylguanidine
4               5-hydroxytryptophan
                   ...
1482                       zotepine
1483                 zuclopenthixol
1484                            성분명
1485                    약독황열생바이러스백신
1486                        영문  성분명
Name: drug, Length: 1487, dtype: object

In [ ]:
com_m2.drug

1          acemetacin
2          acemetacin
3       acetazolamide
4       acetazolamide
5           acitretin
            ...
1168      iodised oil
1169      iodised oil
1170         ioversol
1171        gimeracil
1172      glecaprevir
Name: drug, Length: 2288, dtype: object

In [ ]:
len(set(patient_m3.drug).intersection(set(dup_dg_pr.drug2)).intersection(set(com_m2.drug))), len(set(patient_m3.drug).union(set(dup_dg_pr.drug2)).union(set(com_m2.drug)))

(90, 1921)

In [ ]:
union_dpr = set(patient_m3.drug).union(set(dup_dg_pr.drug2)).union(set(com_m2.drug))

In [ ]:
len(set(top.drug).intersection(set(rxi.drug)).intersection(union_dpr))

134

In [ ]:
len(set(top.drug).intersection(set(rxi.drug)).intersection(union_sp))

93

In [ ]:
img = set(rxi.drug).union(set(pill.drug))

NameError: ignored

In [ ]:
len(set(top.drug).intersection(union_sp))

158

In [ ]:
target_list= list(set(top.drug).intersection(img).intersection(union_sp))

In [ ]:
len(target_list)

107

In [ ]:
list(set(top.drug).intersection(set(rxi.drug)).intersection(union_dpr))

['lithium',
 'linagliptin',
 'venlafaxine',
 'ezetimibe',
 'amoxicillin',
 'indomethacin',
 'warfarin',
 'spironolactone',
 'methylprednisolone',
 'tizanidine',
 'fentanyl',
 'mirtazapine',
 'tretinoin',
 'baclofen',
 'sucralfate',
 'hydrochlorothiazide',
 'citalopram',
 'ondansetron',
 'nystatin',
 'telmisartan',
 'acyclovir',
 'famotidine',
 'clonazepam',
 'dexlansoprazole',
 'glipizide',
 'gemfibrozil',
 'ciprofloxacin',
 'methimazole',
 'ticagrelor',
 'amlodipine',
 'topiramate',
 'aripiprazole',
 'lamotrigine',
 'empagliflozin',
 'lisinopril',
 'olanzapine',
 'primidone',
 'finasteride',
 'irbesartan',
 'atenolol',
 'nabumetone',
 'carbidopa',
 'cyclobenzaprine',
 'canagliflozin',
 'pioglitazone',
 'carbamazepine',
 'oxybutynin',
 'montelukast',
 'colchicine',
 'calcitriol',
 'gabapentin',
 'clonidine',
 'dutasteride',
 'hydroxyzine',
 'terazosin',
 'pregabalin',
 'ketoconazole',
 'sumatriptan',
 'diclofenac',
 'nifedipine',
 'pseudoephedrine',
 'alprazolam',
 'rivaroxaban',
 'ibuprofen',
 'aspirin',
 'levetiracetam',
 'hydrocortisone',
 'ramipril',
 'amitriptyline',
 'rosuvastatin',
 'sulfamethoxazole',
 'celecoxib',
 'isotretinoin',
 'clindamycin',
 'omeprazole',
 'levothyroxine',
 'prednisolone',
 'doxycycline',
 'levofloxacin',
 'duloxetine',
 'modafinil',
 'cetirizine',
 'loratadine',
 'dexamethasone',
 'cefdinir',
 'lorazepam',
 'ranitidine',
 'benzonatate',
 'estradiol',
 'emtricitabine',
 'budesonide',
 'meloxicam',
 'metronidazole',
 'hydroxychloroquine',
 'buprenorphine',
 'furosemide',
 'prednisone',
 'anastrozole',
 'nitroglycerin',
 'fluconazole',
 'erythromycin',
 'paroxetine',
 'bupropion',
 'sildenafil',
 'esomeprazole',
 'ofloxacin',
 'azithromycin',
 'simvastatin',
 'acetaminophen',
 'methotrexate',
 'allopurinol',
 'naproxen',
 'glimepiride',
 'oxcarbazepine',
 'torsemide',
 'diazepam',
 'carvedilol',
 'chlorthalidone',
 'bumetanide',
 'phentermine',
 'guaifenesin',
 'tadalafil',
 'lovastatin',
 'valsartan',
 'metoprolol',
 'fenofibrate',
 'digoxin',
 'risperidone',
 'lansoprazole',
 'docusate',
 'phenytoin',
 'atorvastatin',
 'methocarbamol',
 'letrozole']

In [ ]:
target_list= pd.DataFrame(set(top.drug).intersection(set(rxi.drug)).intersection(union_dpr))
target_list.to_csv('/content/drive/Shareddrives/Codepresso_8/Drug_list/target_list1.csv')

In [ ]:
len(target_list)

29

In [ ]:
rxi_info2.drug

0                           Fentanyl
1                           Fentanyl
2                           Fentanyl
3                           Fentanyl
4                           Fentanyl
                    ...
4187                       Glipizide
4198                    Progesterone
4236                       Glipizide
4254    Chlorpromazine hydrochloride
4268               Lithium Carbonate
Name: drug, Length: 970, dtype: object

In [ ]:
rxi.drug

0          Loperamide
1         Minocycline
2       Nortriptyline
3       Nortriptyline
4       Nortriptyline
            ...
4387        Enalapril
4388        quinapril
4389         trospium
4390       metaxalone
4391      naratriptan
Name: drug, Length: 4332, dtype: object

In [ ]:
target_list= list(set(top.drug).intersection(set(rxi.drug)).intersection(union_sp))

In [ ]:
target_list2= list(set(top.drug).intersection(union_sp))

In [ ]:
target_list3= list(set(top.drug))

In [ ]:
len(target_list), len(target_list2)

(93, 158)

In [ ]:
rxi_target = rxi[rxi['drug'].isin(target_list)]

In [ ]:
len(set(rxi_target.drug))

93

In [ ]:
len(target_list)

93

In [ ]:
target_list

NameError: ignored

In [ ]:
rxi.head()

           ndc11  ...                                    RXBASE ORIGINAL
0  00093-0311-01  ...  image/images/gallery/original/00093-0311-01_NL...
1  00093-3165-01  ...  image/images/gallery/original/00093-3165-01_NL...
2  00093-0810-01  ...  image/images/gallery/original/00093-0810-01_NL...
3  00093-0811-01  ...  image/images/gallery/original/00093-0811-01_NL...
4  00093-0812-01  ...  image/images/gallery/original/00093-0812-01_NL...

[5 rows x 18 columns]

In [ ]:
union_list.sort

In [ ]:
len(set(top.drug).intersection(set(d.drug))), len(set(top.drug).intersection(set(liver.drug))), len(set(top.drug).intersection(set(kidney.drug)))

(54, 70, 70)

In [ ]:
len(set(liver.drug).intersection(set(eldery.drug2))), len(set(kidney.drug).intersection(set(eldery.drug2))), len(set(liver.drug).intersection(set(kidney.drug)))

(71, 54, 94)

In [ ]:
len(set(rxi.drug).intersection(set(top.drug))), len(set(rxi.drug).intersection(set(eldery.drug2))), len(set(rxi.drug).intersection(set(liver.drug))), len(set(rxi.drug).intersection(set(kidney.drug)))

(106, 90, 102, 100)

In [ ]:
len(set(rxi.drug).intersection(set(top.drug).union(set(eldery.drug2).union(set(liver.drug))), len(set(rxi.drug).intersection(set(kidney.drug)))

In [ ]:
liver.head()

                drug  page  liver
idx
1           acarbose    68      1
2        aceclofenac    70      1
3      acetaminophen    70      1
4          acyclovir    72      1
5    alendronic acid    74      1

In [ ]:
com_ph.value_counts()

drug                                     drug2          adr                                                    note                          combination  prohibition
xylometazoline                           selegiline     xylometazoline의 전신작용(고혈압 위험) 증강 또는 연장                                                1            1              1
emtricitabine + tenofovir + rilpivirine  pantoprazole   위장 pH의 증가로 릴피비린의 흡수가 저하되어 릴피비린의 치료효과 감소                                              1            1              1
duloxetine                               moclobemide    세로토닌 증후군 위험 증가 가능성                                                                   1            1              1
                                         selegiline     세로토닌 증후군 위험 증가 가능성                                                                   1            1              1
emtricitabine + tenofovir + rilpivirine  carbamazepine  릴피비린의 혈중농도가 감소하여 치료효과 감소 혹은 내성 발현                                                    1            1              1
                                                                                                                                                                        ..
metformin + rosiglitazone                iomeprol       기능적 신부전에 의해 유산 산성증 촉진                                  48시간 이내 병용금기                  1            1              1
                                         iopamidol      기능적 신부전에 의해 유산 산성증 촉진                                  48시간 이내 병용금기                  1            1              1
                                         iopromide      기능적 신부전에 의해 유산 산성증 촉진                                  48시간 이내 병용금기                  1            1              1
                                         iotrolan       기능적 신부전에 의해 유산 산성증 촉진                                  48시간 이내 병용금기                  1            1              1
acemetacin                               methotrexate   신세뇨관에서 Methotrexate 배설이 지연되어 Methotrexate의 혈액학적 독성 증가  methotrexate 1주에 15mg 이상 투여시  1            1              1
Length: 336, dtype: int64

In [ ]:
len(com_ph.comp1.unique())

312

In [ ]:
len(drug_101.name)

101

In [ ]:
len(set(drug_101.name))

101

# Relation_Table

In [ ]:
dur.head()

   DUR일련번호 DUR유형 단일복합구분코드  ...           병용금기약효분류   비고  상태
0     4050  병용금기       복합  ...        [01130]항전간제  NaN  정상
1     4058  병용금기       복합  ...  [01190]기타의 중추신경용약  NaN  정상
2     4078  병용금기       복합  ...   [06290]기타의 화학요법제  NaN  정상
3     4328  병용금기       복합  ...       [01230]자율신경제  NaN  정상
4     4330  병용금기       복합  ...       [01230]자율신경제  NaN  정상

[5 rows x 26 columns]

In [ ]:
dur.shape, dur.columns

((1173, 26),
 Index(['DUR일련번호', 'DUR유형', '단일복합구분코드', 'DUR성분코드', 'DUR성분명영문', 'DUR성분명', '복합제',
        '관계성분', '약효분류코드', '효능군', '고시일자', '금기내용', '제형', '연령기준', '최대투여기간',
        '1일최대용량', '등급', '병용금기단일복합구분코드', '병용금기DUR성분코드', '병용금기DUR성분명',
        '병용금기DUR성분명.1', '병용금기복합제', '병용금기관계성분', '병용금기약효분류', '비고', '상태'],
       dtype='object'))

In [ ]:
#dur[['DUR성분코드', 'DUR성분명영문', 'DUR성분명']]
durr= dur[['DUR성분코드', 'DUR성분명영문', 'DUR성분명', '복합제', '관계성분', '약효분류코드',  '병용금기DUR성분코드', '병용금기DUR성분명','병용금기복합제', '병용금기관계성분', '병용금기약효분류']]
durr.columns = ['DUR_code', 'drug', 'k_drug', 'comp', 'relation', 'class', 'DUR_code2', 'drug2', 'comp2', 'relation2', 'class2']

In [ ]:
durr['drug'] = durr['drug'].str.lower()
durr['drug2'] = durr['drug2'].str.lower()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
durr

     DUR_code  ...             class2
0     D001171  ...        [01130]항전간제
1     D001171  ...  [01190]기타의 중추신경용약
2     D000749  ...   [06290]기타의 화학요법제
3     D000018  ...       [01230]자율신경제
4     D000018  ...       [01230]자율신경제
...       ...  ...                ...
1168  D000032  ...       [03960]당뇨병용제
1169  D000032  ...       [03960]당뇨병용제
1170  D000165  ...       [03960]당뇨병용제
1171  D000080  ...                NaN
1172  D001362  ...                NaN

[1173 rows x 11 columns]

In [ ]:
durr[['drug', 'drug2']]

                         drug           drug2
0                    elbasvir   carbamazepine
1                    elbasvir  st. johns wort
2           ethinyl estradiol      ombitasvir
3     bupropion hydrochloride  diethylpropion
4     bupropion hydrochloride      lorcaserin
...                       ...             ...
1168              iodised oil       metformin
1169              iodised oil       metformin
1170                 ioversol       metformin
1171                gimeracil    fluorouracil
1172              glecaprevir   carbamazepine

[1173 rows x 2 columns]

In [ ]:
com_ph[['drug', 'drug2']]

                           drug                       drug2
연번
1                    acemetacin                  diflunisal
2                    acemetacin                methotrexate
3                 acetazolamide               methazolamide
4                 acetazolamide                  topiramate
5                     acitretin                doxycycline
...                         ...                         ...
1119                 letermovir           methylergometrine
1120  netupitant + palonosetron                  rifampicin
1121                 tegoprazan                  atazanavir
1122                 tegoprazan                 rilpivirine
1123                 tegoprazan  rilpivirine + dolutegravir

[1115 rows x 2 columns]

In [ ]:
durr[['drug', 'drug2', 'adr']]

                         drug  ...                                                adr
0                    elbasvir  ...  엘바스비르와 그라조프레비르의 혈장 농도가 유의하게 감소하여 이 약의 바이러스학적 반...
1                    elbasvir  ...  엘바스비르와 그라조프레비르의 혈장 농도가 유의하게 감소하여 이 약의 바이러스학적 반...
2           ethinyl estradiol  ...        ALT 수치가 정상치 상한 기준보다 20배 이상 높게 나타나는 데 영향이 있음
3     bupropion hydrochloride  ...                                           판막심장병 위험
4     bupropion hydrochloride  ...                                      안전성 및 유효성 미확립
...                       ...  ...                                                ...
1168              iodised oil  ...                              기능적 신부전에 의해 유산 산성증 촉진
1169              iodised oil  ...                              기능적 신부전에 의해 유산 산성증 촉진
1170                 ioversol  ...                              기능적 신부전에 의해 유산 산성증 촉진
1171                gimeracil  ...  해당 약물 병용 시 gimeracil에 의해 fluoropyrimidine 계열 약...
1172              glecaprevir  ...  Glecaprevir와 Pibrentasvir의 혈장 농도가 유의하게 감소하여 이 ...

[1173 rows x 3 columns]

In [ ]:
com_ph.columns = ['drug', 'drug2', 'adr', 'note', 'combination', 'prohibition']

In [ ]:
com_m2 = pd.concat([com_ph, durr[['drug', 'drug2', 'adr']]], join = 'outer', axis = 0)

In [ ]:
com_m2['combination'] = 1
com_m2['prohibition'] = 1
com_m3 = com_m2.drop_duplicates(subset = ['drug', 'drug2', 'adr'])

In [ ]:
com_m3.to_csv('./relation_m2.csv', sep=',')
com_m3

               drug          drug2  ... combination prohibition
1        acemetacin     diflunisal  ...           1           1
2        acemetacin   methotrexate  ...           1           1
3     acetazolamide  methazolamide  ...           1           1
4     acetazolamide     topiramate  ...           1           1
5         acitretin   doxycycline   ...           1           1
...             ...            ...  ...         ...         ...
1140    glecaprevir     atazanavir  ...           1           1
1141    glecaprevir   atorvastatin  ...           1           1
1151      gimeracil   capecitabine  ...           1           1
1171      gimeracil   fluorouracil  ...           1           1
1172    glecaprevir  carbamazepine  ...           1           1

[1719 rows x 6 columns]

In [ ]:
durr.columns

Index(['DUR_code', 'drug', 'k_drug', 'comp', 'relation', 'class', 'adr', 'age',
       'period', 'dosage', 'grade', 'DUR_code2', 'drug2', 'comp2', 'relation2',
       'class2', 'combination', 'prohibition'],
      dtype='object')

In [ ]:
durr.to_csv('./durr.csv', sep=',')

In [ ]:
com_m4 = pd.concat([com_ph, durr[['drug', 'drug2', 'adr','age','period','dosage','grade']]], join = 'outer', axis = 0)
com_m4['combination'] = 1
com_m4['prohibition'] = 1
com_m5 = com_m4.drop_duplicates(subset = ['drug', 'drug2', 'adr'])
com_m5

               drug          drug2  ... dosage grade
1        acemetacin     diflunisal  ...    NaN   NaN
2        acemetacin   methotrexate  ...    NaN   NaN
3     acetazolamide  methazolamide  ...    NaN   NaN
4     acetazolamide     topiramate  ...    NaN   NaN
5         acitretin   doxycycline   ...    NaN   NaN
...             ...            ...  ...    ...   ...
1140    glecaprevir     atazanavir  ...    NaN   NaN
1141    glecaprevir   atorvastatin  ...    NaN   NaN
1151      gimeracil   capecitabine  ...    NaN   NaN
1171      gimeracil   fluorouracil  ...    NaN   NaN
1172    glecaprevir  carbamazepine  ...    NaN   NaN

[1719 rows x 10 columns]

In [ ]:
com_m5.drug.unique()

array(['acemetacin', 'acetazolamide', 'acitretin', 'adefovir ',
       'adefovir', 'alfacalcidol', 'almotriptan ', 'almotriptan',
       'alprazolam', 'altretamine', 'amantadine', 'amantadine ',
       'amiloride', 'aminocaproic acid', 'amiodarone ', 'amisulpride',
       'amitriptyline ', 'amoxapine', 'amrinone ', 'anastrozole',
       'caffeine + ergotamine', 'apraclonidine ',
       'articaine + epinephrine', 'aspirin', 'aspirin + dipyridamole',
       'atazanavir', 'atazanavir ', 'atomoxetine ', 'atorvastatin ',
       'auranofin', 'avanafil', 'azithromycin', 'benserazide + levodopa',
       'blonanserin', 'bosentan', 'brimonidine ', 'bromperidol',
       'buprenorphine', 'buspirone', 'buspirone ', 'calcifediol',
       'calcitriol', 'carbamazepine', 'chlorpromazine ',
       'chlorprothixene', 'chlorthalidone', 'citalopram', 'citalopram ',
       'clarithromycin', 'clenbuterol ', 'clomipramine ', 'cyclosporine',
       'dapoxetine', 'dapoxetine ', 'darunavir ', 'dexamethasone',
       'dexketoprofen ', 'diethylpropion ', 'diflunisal ',
       'dihydroergotamine ', 'divalproex', 'dothiepin ', 'doxepin ',
       'doxycycline', 'dronedarone ', 'efavirenz', 'ephedrine ',
       'ergotamine ', 'ergotamine', 'erythromycin', 'erythromycin ',
       'esomeprazole ', 'ezetimibe + simvastatin', 'fenoterol ',
       'flecainide ', 'fluconazole', 'fluoxetine ', 'fluvoxamine ',
       'formoterol ', 'gentamicin ', 'glibenclamide', 'gliclazide',
       'glipizide', 'haloperidol', 'hemocoagulase', 'hexoprenaline ',
       'hydrochlorothiazide', 'hydrocortisone', 'ibuprofen', 'ilaprazole',
       'imipramine ', 'indinavir ', 'indometacin', 'iobitridol',
       'iodixanol', 'iohexol', 'iomeprol', 'iopamidol', 'iopromide',
       'iotrolan', 'ioversol', 'ioxaglate', 'isoproterenol ',
       'isosorbide dinitrate', 'isosorbide mononitrate', 'isotretinoin',
       'itraconazole', 'ketoconazole', 'ketoprofen', 'ketorolac ',
       'lansoprazole', 'levomepromazine ', 'lovastatin', 'mazindol',
       'meloxicam', 'melphalan', 'menatetrenon', 'metacycline ',
       'metformin ', 'metformin + glibenclamide',
       'metformin + gliclazide', 'metformin + glimepiride',
       'metformin + pioglitazone ', 'metformin + rosiglitazone',
       'metformin + sitagliptin ', 'metformin + vildagliptin ',
       'methoxyphenamine ', 'methylergometrine ', 'methylphenidate',
       'methylprednisolone', 'metolazone', 'metronidazole + spiramycin',
       'midazolam', 'midecamycin', 'minocycline ', 'mirodenafil',
       'mirodenafil ', 'mirtazapine', 'mizolastine', 'moclobemide',
       'molsidomine', 'naratriptan ', 'nelfinavir ', 'netilmicin ',
       'nicorandil', 'nisoldipine', 'norepinephrine ', 'nortriptyline ',
       'octreotide ', 'omeprazole', 'oxapium iodide', 'oxatomide',
       'pantoprazole', 'paricalcitol', 'paroxetine ', 'pentamidine ',
       'perphenazine', 'pethidine ', 'phendimetrazine ', 'phentermine ',
       'phentermine', 'pimozide', 'piroxicam ', 'posaconazole',
       'potassium chloride', 'potassium citrate', 'prednisolone',
       'procaterol ', 'proglumetacin ', 'pseudoephedrine', 'quazepam',
       'quinidine ', 'quinidine', 'quinupramine', 'rabeprazole ',
       'repaglinide', 'revaprazan ', 'rifampicin', 'rifampicin ',
       'ritonavir', 'roxithromycin', 'salbutamol', 'salbutamol ',
       'selegiline ', 'sibutramine', 'sildenafil', 'sildenafil ',
       'simvastatin', 'spiramycin', 'spironolactone', 'sumatriptan ',
       'tacrolimus', 'tadalafil', 'telithromycin', 'tenoxicam',
       'terbutaline ', 'thiothixene', 'tiaprofenic acid ', 'tizanidine ',
       'tranexamic acid', 'tretinoin', 'triazolam', 'trifluoperazine ',
       'tulobuterol ', 'udenafil', 'valproic acid ', 'vardenafil',
       'vardenafil ', 'ziprasidone ', 'zolmitriptan', 'zuclopenthixol ',
       'cyproterone + ethinyl estradiol', 'dexlansoprazole',
       'esomeprazole', 'olanzapine', 'agomelatine', 'dabigatran ',
       'doripenem', 'etravirine', 'febuxostat', 'fosaprepitant',
       'iguratimod', 'ivabradine', 'rasagiline', 'rilpivirine',
       'rivaroxaban', 'silodosin', 'ticagrelor', 'tolvaptan',
       'domperidone', 'lamivudine', 'lamivudine + zidovudine',
       'lamivudine + abacavir ', 'xylometazoline ', 'boceprevir',
       'dolutegravir ', 'emtricitabine + tenofovir + rilpivirine',
       'emtricitabine + tenofovir + rilpivirine ', 'desvenlafaxine',
       'vortioxetine', 'etoricoxib', 'tapentadol',
       'trastuzumab emtansine', 'duloxetine', 'risperidone', 'quetiapine',
       'diltiazem', 'verapamil', 'diclofenac + misoprostol',
       'nitroglycerin', 'dextromethorphan', 'ephedrine',
       'simvastatin + ezetimibe', 'simvastatin + fenofibrate',
       'st. john’s wort', 'asunaprevir', 'daclatasvir', 'sofosbuvir',
       'ledipasvir + sofosbuvir', 'omeprazole+sodium bicarbonate',
       'esomeprazole+naproxen', 'atorvastatin', 'atorvastatin+amlodipine',
       'atorvastatin+ezetimibe', 'atorvastatin+irbesartan', 'hydroxyzine',
       'oxymetazoline', 'dabigatran', 'sertraline', 's-pantoprazole',
       'palbociclib', 'elbasvir + grazoprevir', 'ethinylestradiol',
       'ethinylestradiol + gestodene',
       'ethinylestradiol + levonorgestrel',
       'ethinylestradiol + desogestrel',
       'ethinylestradiol + drospirenone',
       'ethinylestradiol + cyproterone', 'methotrexate', 'gemfibrozil',
       'bupropion+naltrexone', 'lorcaserin',
       'cobicistat+elvitegravir+emtricitabine+tenofovir ',
       'radium 223 dichloride', 'voriconazole', 'rosuvastatin',
       'pitavastatin', 'iodised oil',
       'dexbrompheniramine + pseudoephedrine',
       'gimeracil + oteracil + tegafur',
       'sulfamethoxazole + trimethoprim', 'glecaprevir + pibrentasvir',
       'letermovir', 'netupitant + palonosetron', 'tegoprazan',
       'elbasvir', 'ethinyl estradiol', 'bupropion hydrochloride',
       'ledipasvir', 'st. johns wort', 'dabigatran etexilate',
       'ketorolac', 'fluoxetine', 'fluvoxamine',
       'selegiline hydrochloride', 'imipramine', 'nelfinavir',
       'pentamidin', 'nortriptyline', 'trifluoperazine',
       'dihydroergotamine', 'amiodarone', 'naratriptan', 'isoproterenol',
       'indinavir', 'methylergometrine', 'sumatriptan', 'chlorpromazine',
       'clenbuterol', 'ioxaglic acid', 'menatetrenone', 'octreotide',
       'procaterol', 'pethidine', 'fenoterol', 'isosorbide',
       'flecainide acetate', 'darunavir', 'diethylpropion', 'piroxicam',
       'ezetimibe', 'metformin', 'phendimetrazine tartrate',
       'tulobuterol', 'dipyridamole', 'adefovir dipivoxil',
       'dexketoprofen', 'ziprasidone', 'dronedarone', 'quazepam ',
       'tizanidine', 'norepinephrine', 'terbutaline sulfate',
       'revaprazan', 'methoxyphenamine', 'gentamicin', 'methacycline',
       'trometamol', 'articaine', 'atomoxetine', 'levomepromazine',
       'rabeprazole', 'netilmicin', 'cyproterone',
       'fosaprepitant dimeglumine', 'clomipramine', 'minocycline',
       'amitriptyline', 'benserazide', 'hexoprenaline', 'formoterol',
       'amrinone', 'xylometazoline', 'zuclopenthixol', 'dothiepin',
       'tiaprofenic acid', 'valproic acid', 'emtricitabine',
       'dolutegravir', 'diclofenac', 'paroxetine', 'brimonidine',
       'metronidazole', 'apraclonidine', 'doxepin', 'proglumetacin',
       'buprenorpine', 'diflunisal', 'cobicistat', 'sulfamethoxazole',
       'glecaprevir', 'netupitant', 'dexbrompheniramine', 'gimeracil'],
      dtype=object)

In [ ]:
com_ph.to_csv('./relation_1_adr.csv', sep=',')

In [ ]:
durr[['drug', 'drug2']].groupby('drug').apply(lambda group: ', '.join(group['drug2']))

drug
acemetacin                                     methotrexate, diflunisal
acetazolamide                                 methazolamide, topiramate
acitretin             doxycycline, minocycline, tetracycline, methot...
adefovir dipivoxil                             emtricitabine, tenofovir
agomelatine                                  fluvoxamine, ciprofloxacin
                                            ...
vortioxetine                      selegiline hydrochloride, moclobemide
xylometazoline        moclobemide, selegiline hydrochloride, rasagiline
ziprasidone              dronedarone, pimozide, mizolastine, toremifene
zolmitriptan                                                moclobemide
zuclopenthixol                                              epinephrine
Length: 248, dtype: object

In [ ]:
com_ph[['drug', 'drug2']].groupby('drug').apply(lambda group: ', '.join(group['drug2']))

drug
acemetacin                                  diflunisal, methotrexate
acetazolamide                              methazolamide, topiramate
acitretin          doxycycline , methotrexate, minocycline , oxyt...
adefovir                                                  tenofovir
adefovir                                   emtricitabine + tenofovir
                                         ...
vortioxetine                                moclobemide, selegiline
xylometazoline                  moclobemide, rasagiline , selegiline
ziprasidone          dronedarone, mizolastine, pimozide, toremifene
zolmitriptan                                             moclobemide
zuclopenthixol                                           epinephrine
Length: 295, dtype: object

In [ ]:
com_ph['drug'] = com_ph['drug'].apply(lambda x : cleantt(x))
com_ph['drug2'] = com_ph['drug2'].apply(lambda x : cleantt(x))
durr['drug'] = durr['drug'].apply(lambda x : cleantt(x))
durr['drug2'] = durr['drug2'].apply(lambda x : cleantt(x))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [ ]:
com_ph[['drug', 'drug2']].groupby('drug')

In [ ]:
com_ph_g = pd.DataFrame(com_ph[['drug', 'drug2']].groupby('drug').apply(lambda group: ', '.join(group['drug2'])))
durr_g = pd.DataFrame(durr[['drug', 'drug2']].groupby('drug').apply(lambda group: ', '.join(group['drug2'])))

In [ ]:
com_ph_g = pd.DataFrame(com_ph.groupby('drug').apply(lambda group: ', '.join(group['drug2'])))

In [ ]:
pd.merge(com_ph_g, durr_g, on = 'drug', how = 'outer')

                                                              0_x                                                0_y
drug
acemetacin                               diflunisal, methotrexate                           methotrexate, diflunisal
acetazolamide                           methazolamide, topiramate                          methazolamide, topiramate
acitretin       doxycycline , methotrexate, minocycline , oxyt...  doxycycline, minocycline, tetracycline, methot...
adefovir                                               tenofovir                                                 NaN
adefovir                                emtricitabine + tenofovir                                                NaN
...                                                           ...                                                ...
tulobuterol                                                   NaN                        epinephrine, norepinephrine
valproic acid                                                 NaN  meropenem, imipenem, panipenem, imipenem, pani...
xylometazoline                                                NaN  moclobemide, selegiline hydrochloride, rasagiline
ziprasidone                                                   NaN     dronedarone, pimozide, mizolastine, toremifene
zuclopenthixol                                                NaN                                        epinephrine

[384 rows x 2 columns]

In [ ]:
com_ph_g.columns = ['drug2']
durr_g.columns = ['drug2']

In [ ]:
com_ph_g

                                                             drug2
drug
acemetacin                                diflunisal, methotrexate
acetazolamide                            methazolamide, topiramate
acitretin        doxycycline , methotrexate, minocycline , oxyt...
adefovir                                                tenofovir
adefovir                                 emtricitabine + tenofovir
...                                                            ...
vortioxetine                              moclobemide, selegiline
xylometazoline                moclobemide, rasagiline , selegiline
ziprasidone        dronedarone, mizolastine, pimozide, toremifene
zolmitriptan                                           moclobemide
zuclopenthixol                                         epinephrine

[295 rows x 1 columns]

In [ ]:
relation_list = pd.merge(com_ph_g, durr_g, on = ['drug', 'drug2'], how = 'outer')

In [ ]:
def cleantt(readData):
 
    #텍스트에 포함되어 있는 특수 문자 제거
 
    text = re.sub(r'\([^)]*\)', '', readData)
 
    return text
relation_list['drug2'] = relation_list['drug2'].apply(lambda x : cleantt(x))

In [ ]:
relation_list['combination'] = 1
relation_list['prohibitioin'] = 1

In [ ]:
relation_list

                                                            drug2  ...  prohibitioin
drug                                                               ...
acemetacin                               diflunisal, methotrexate  ...             1
acetazolamide                           methazolamide, topiramate  ...             1
acitretin       doxycycline , methotrexate, minocycline , oxyt...  ...             1
adefovir                                               tenofovir   ...             1
adefovir                                emtricitabine + tenofovir  ...             1
...                                                           ...  ...           ...
voriconazole    rifabutin, phenobarbital, sirolimus, st. johns...  ...             1
vortioxetine                selegiline hydrochloride, moclobemide  ...             1
xylometazoline  moclobemide, selegiline hydrochloride, rasagiline  ...             1
ziprasidone        dronedarone, pimozide, mizolastine, toremifene  ...             1
zuclopenthixol                                        epinephrine  ...             1

[496 rows x 3 columns]

In [ ]:
relation_list.to_csv("./relation_dur.csv")

In [ ]:
import re
 
def cleanText(readData):
 
    #텍스트에 포함되어 있는 특수 문자 제거
 
    text = re.sub('[-=+,#/\?:^$.@*\"※~&%ㆍ!』\\‘|\(\)\[\]\<\>`\'…》]', '', readData)
 
    return text

def cleant(readData):
 
    #텍스트에 포함되어 있는 특수 문자 제거
 
    text = re.sub(r'[\(*)*\)]', '', readData)
 
    return text

def cleantt(readData):
 
    #텍스트에 포함되어 있는 특수 문자 제거
 
    text = re.sub(r'\([^)]*\)', '', readData)
 
    return text

def cleant2(readData):
 
    #텍스트에 포함되어 있는 특수 문자 제거
 
    text = re.sub(r'\[[^)]*\]', '', readData)
 
    return text

In [ ]:
relation_list['drug2'][0]

'diflunisal, methotrexate(분류번호 : 421)'

In [ ]:
cleantt(relation_list['drug2'][0])

'diflunisal, methotrexate'

In [ ]:
cleant2(durr['drug2'][0])

'carbamazepine'

In [ ]:
durr[['drug', 'class']].dropna()

                         drug                       class
0                    elbasvir            [06290]기타의 화학요법제
1                    elbasvir            [06290]기타의 화학요법제
2           ethinyl estradiol  [02490]기타의 호르몬제(항호르몬제를 포함)
3     bupropion hydrochloride                [01230]자율신경제
4     bupropion hydrochloride                [01230]자율신경제
...                       ...                         ...
1166                iopromide                [07210]X선조영제
1167                iopromide                [07210]X선조영제
1168              iodised oil                [07210]X선조영제
1169              iodised oil                [07210]X선조영제
1170                 ioversol                [07210]X선조영제

[1151 rows x 2 columns]

In [ ]:
durr_class1 = durr[['drug', 'class']]
durr_class2 = durr[['drug2', 'class2']]
durr_class2.columns = ['drug', 'class']

In [ ]:
durr_class1.dropna(inplace=True)
durr_class2.dropna(inplace=True)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
durr_class1['class'] = durr_class1['class'].apply(lambda x : cleant2(x))
durr_class2['class'] = durr_class2['class'].apply(lambda x : cleant2(x))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
durr_class1

                         drug                class
0                    elbasvir            기타의 화학요법제
1                    elbasvir            기타의 화학요법제
2           ethinyl estradiol  기타의 호르몬제(항호르몬제를 포함)
3     bupropion hydrochloride                자율신경제
4     bupropion hydrochloride                자율신경제
...                       ...                  ...
1166                iopromide                X선조영제
1167                iopromide                X선조영제
1168              iodised oil                X선조영제
1169              iodised oil                X선조영제
1170                 ioversol                X선조영제

[1151 rows x 2 columns]

In [ ]:
pd.concat([durr_class1, durr_class2], axis= 0, join = 'outer')

                         drug                class
0                    elbasvir            기타의 화학요법제
1                    elbasvir            기타의 화학요법제
2           ethinyl estradiol  기타의 호르몬제(항호르몬제를 포함)
3     bupropion hydrochloride                자율신경제
4     bupropion hydrochloride                자율신경제
...                       ...                  ...
1166                metformin                당뇨병용제
1167                metformin                당뇨병용제
1168                metformin                당뇨병용제
1169                metformin                당뇨병용제
1170                metformin                당뇨병용제

[2303 rows x 2 columns]

In [ ]:
#pd.merge(durr_class1, durr_class2, on = ['drug', 'class'], how = 'outer')

                 drug              class
0            elbasvir          기타의 화학요법제
1            elbasvir          기타의 화학요법제
2            elbasvir          기타의 화학요법제
3            elbasvir          기타의 화학요법제
4            elbasvir          기타의 화학요법제
...               ...                ...
14094  pentoxifylline          기타의 순환계용약
14095     abiraterone             항악성종양제
14096   lercanidipine              혈압강하제
14097      felodipine              혈압강하제
14098       alfuzosin  기타의 비뇨생식기관 및 항문용약

[14099 rows x 2 columns]

In [ ]:
pd.concat([durr_class1, durr_class2], axis= 0, join = 'outer').duplicated(keep = 'first')

0       False
1        True
2       False
3       False
4        True
        ...
1168     True
1169     True
1170     True
1171    False
1172    False
Length: 2346, dtype: bool

In [ ]:
dur_class_m = pd.concat([durr_class1, durr_class2], axis= 0, join = 'inner')
dur_class_m = dur_class_m.drop_duplicates()
dur_class_m

NameError: ignored

In [ ]:
dur_class_m2 = dur_class_m.groupby('drug').sum()

In [ ]:
!pwd

/content/drive/Shareddrives/Codepresso_8/Drug_list/final_data

In [ ]:
dur_class_m2.to_csv('/content/drive/Shareddrives/Codepresso_8/Drug_list/dur_class_m2.csv')

In [ ]:
#groupby(['FIRST_NM', 'LAST_NM']).apply(lambda group: ','.join(group['PAGE_NUM']))
dur_class_m.groupby('drug').apply(lambda group: ','.join(group['class']))

TypeError: ignored

In [ ]:
durr[['drug', 'drug2']]

                         drug           drug2
0                    elbasvir   carbamazepine
1                    elbasvir  st. johns wort
2           ethinyl estradiol      ombitasvir
3     bupropion hydrochloride  diethylpropion
4     bupropion hydrochloride      lorcaserin
...                       ...             ...
1168              iodised oil       metformin
1169              iodised oil       metformin
1170                 ioversol       metformin
1171                gimeracil    fluorouracil
1172              glecaprevir   carbamazepine

[1173 rows x 2 columns]

In [ ]:
len(set(com_ph.drug)), len(set(com_ph.drug2)), len(set(durr.drug)), len(set(durr.drug2)), len(set(com_ph.drug).union(set(com_ph.drug2))), len(set(durr.drug).union(set(durr.drug2)))

(312, 433, 248, 281, 608, 383)

In [ ]:
set_com = set(com_ph.drug).union(set(com_ph.drug2))
set_durr = set(durr.drug).union(set(durr.drug2))

In [ ]:
len(set_com.intersection(set_durr)), len(set_com.union   (set_durr))

(75, 916)

In [ ]:
len(set(rxi_list).intersection(set(com_ph.drug)))

NameError: ignored

In [ ]:
# import json
# with open('E:/datasets/patients.json', 'w') as f:
#     json.dump(patients, f)

# RXImage table

In [ ]:
rxi.head()

           ndc11   rxcui  ...           drug  rxi
0  00093-0311-01  978006  ...     loperamide    1
1  00093-3165-01  197985  ...    minocycline    1
2  00093-0810-01  198045  ...  nortriptyline    1
3  00093-0811-01  317136  ...  nortriptyline    1
4  00093-0812-01  198046  ...  nortriptyline    1

[5 rows x 20 columns]

In [ ]:
rxi_meta = pd.read_json("/content/drive/Shareddrives/Codepresso_8/rximage_set/MONGOexport/rximagesAll.json", lines=True)

In [ ]:
rxi_meta.shape

(4392, 35)

In [ ]:
rxi_meta.head()

                                    _id          ndc11  ...  splRootId  splVersion
0  {'$oid': '5a32f687eb4525ea9e82bee3'}  63459-0502-30  ...        NaN         NaN
1  {'$oid': '5a32f687eb4525ea9e82bee4'}  63459-0504-30  ...        NaN         NaN
2  {'$oid': '5a32f687eb4525ea9e82bee5'}  63459-0506-30  ...        NaN         NaN
3  {'$oid': '5a32f687eb4525ea9e82bee6'}  63459-0508-30  ...        NaN         NaN
4  {'$oid': '5a32f687eb4525ea9e82bee7'}  63459-0512-30  ...        NaN         NaN

[5 rows x 35 columns]

In [ ]:
rxi_meta.mpc[0].keys()

dict_keys(['shape', 'size', 'color', 'imprint', 'imprintColor', 'imprintType', 'symbol', 'score'])

In [ ]:
rxi_mett = rxi_meta[['ndc11', 'name', 'mpc', 'rxnavImageFileName', 'nlmImageFileName']]

In [ ]:
rxi_mpc = rxi_meta['mpc'].apply(pd.Series)

In [ ]:
rxi_mett.shape, rxi_mpc.shape

((4392, 5), (4392, 8))

In [ ]:
rxi_info = pd.concat([rxi_mett, rxi_mpc], axis = 1)

In [ ]:
rxi_info.isnull().sum()

ndc11                    0
name                     0
mpc                      0
rxnavImageFileName       0
nlmImageFileName         0
shape                    0
size                     0
color                    0
imprint                 21
imprintColor          3408
imprintType             13
symbol                   0
score                    0
dtype: int64

In [ ]:
rxi_info.dropna(axis = 0, inplace=True)
rxi_info['name'] = rxi_info['name'].str.lower()
rxi_info2['name'] = rxi_info2['name'].str.lower()
rxi_info['drug'] = rxi_info['name'].str.lower().apply(lambda x : x.split(' ')[0])
#rxi_info['dose'] = rxi_info['name'].apply(lambda x : x.split(' ')[1])

In [ ]:
rxi_info['drug2'] = rxi_info['name'].apply(lambda x : re.search('[A-Z|a-z|]{3,}[A-Z|a-z|\s]{3,}', x))

In [ ]:
rxi_info2 = rxi_info.dropna(axis=0)

In [ ]:
pwd

'/content/drive/Shareddrives/Codepresso_8/Drug_list/final_data'

In [ ]:
rxi_info2 = rxi_info2.apply(lambda x : x.astype(str).str.lower())
rxi_info2.to_csv('/content/drive/Shareddrives/Codepresso_8/Drug_list/rxi_info2.csv')

In [ ]:
len(rxi_info.drug.unique()), len(rxi_info2.drug.unique()), len(rxi_info2.drug3.unique())

(167, 167, 197)

In [ ]:
set(rxi_info.drug).difference(set(rxi_info2.drug))

{''}

In [ ]:
rxi_info.dropna(axis = 0, inplace=True)
rxi_info['drug'] = rxi_info['name'].apply(lambda x : x.split(' ')[0])
#rxi_info['drug2'] = rxi_info['name'].apply(lambda x : re.search('[A-Z|a-z|]{3,}[A-Z|a-z|\s]{3,}', x))

def drug_name(x):
  re.search('[A-Z|a-z|]{3,}[A-Z|a-z|\s]{3,}', x)
rxi_info['drug2'] = rxi_info['name'].apply(lambda x : drug_name(x))

In [ ]:
rxi_info2['drug'] = rxi_info2['name'].apply(lambda x : re.search('[A-Z|a-z|]{3,}', x).group(0).rstrip(' '))
rxi_info2['drug2'] = rxi_info2['name'].apply(lambda x : re.search('[A-Z|a-z|]{3,}[A-Z|a-z|\s]{3,}', x).group(0).rstrip(' '))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
rxi_info.shape, rxi_info2.shape

((970, 15), (970, 16))

In [ ]:
len(set(rxi_info2.drug3)), len(set(rxi_info2.drug2)), len(set(rxi_info2.drug))

(197, 970, 167)

In [ ]:
len(set(rxi_info2.drug3).intersection(target_list)), len(set(rxi_info2.drug2).intersection(target_list)), len(set(rxi_info2.drug).intersection(target_list))

(41, 33, 29)

In [ ]:
len(set(rxi_info2.drug3).intersection(target_list2)), len(set(rxi_info2.drug2).intersection(target_list2)), len(set(rxi_info2.drug).intersection(target_list2))

(42, 33, 29)

In [ ]:
len(set(rxi_info2.drug3).intersection(set(rxi.drug))), len(set(rxi_info2.drug2).intersection(set(rxi.drug))), len(set(rxi_info2.drug).intersection(set(rxi.drug)))

(185, 168, 117)

In [ ]:
len(set(rxi.drug))

512

In [ ]:
rxi_info2

              ndc11  ...           drug3
0     63459-0502-30  ...        Fentanyl
1     63459-0504-30  ...        Fentanyl
2     63459-0506-30  ...        Fentanyl
3     63459-0508-30  ...        Fentanyl
4     63459-0512-30  ...        Fentanyl
...             ...  ...             ...
4187  10370-0191-05  ...       Glipizide
4198  00032-1708-01  ...    Progesterone
4236  10370-0190-01  ...       Glipizide
4254  00832-0302-00  ...  Chlorpromazine
4268  64980-0205-01  ...         Lithium

[970 rows x 16 columns]

In [ ]:
c = 'Lithium Carbonate 300 MG Extended Release Oral'
re.search('[A-Z|a-z|]{3,}[A-Z|a-z|\s]{3,}', c).group().rstrip(' ')

'Lithium Carbonate'

In [ ]:
def drug_name(x):
  re.search('[A-Z|a-z|]{3,}[A-Z|a-z|\s]{3,}', x).group().rstrip(' ')

In [ ]:
rxi_info['drug'] = rxi_info['name'].apply(lambda x : re.search('[A-Z|a-z|]{3,}[A-Z|a-z|\s]{3,}', x))

In [ ]:
x = '24 HR Glipizide 10 MG Extended Release Oral Ta'
re.search('[A-Z|a-z|]{3,}[A-Z|a-z|\s]{3,}', x).group().rstrip(' ')

'Glipizide'

In [ ]:
x = 'Chlorpromazine hydrochloride 50 MG Oral Tablet'
re.search('[A-Za-z]+![0-9]', x)

In [ ]:
x = 'Chlorpromazine hydrochloride 50 MG Oral Tablet'
y = '24 HR Glipizide 10 MG Extended Release Oral Ta'
a = re.search('[A-Z|a-z|\s]+', x)
re.search('[A-Z|a-z|\s]+', y)

In [ ]:
cc = '24 HR lamotrigine 100 MG Extended Release Oral Tablet [Lamictal]'
re.search('[A-Z|a-z|]{3,}[A-Z|a-z|\s]{3,}', cc).group()

'lamotrigine '

In [ ]:
a = re.match('[A-Z|a-z|\s]+', x)
a.group(0).rstrip(' ')

'Chlorpromazine hydrochloride'

In [ ]:
re.search('[A-Z|a-z|]{3,}[A-Z|a-z|\s]{3,}', y).group(0).rstrip(' ')

'Glipizide'

In [ ]:
y = '24 HR Glipizide 10 MG Extended Release Oral Ta'

In [ ]:
re.search('[A-Za-z|\s]+', y)

In [ ]:
re.search('[A-Za-z|\s]+[0-9]+', y).group().split(' ')[-2]

'Glipizide'

In [ ]:
re.search('[A-Za-z|\s]+[0-9]+', x).group().split(' ')[-2]

'hydrochloride'

In [ ]:
len(set(rxi_info2.ndc11)), len(set(rxi.ndc11))

(950, 4179)

In [ ]:
len(rxi.ndc11)

4332

In [ ]:
len(rxi_info2.drug.unique())

168

In [ ]:
pd.merge(rxi_info, rxi, on= 'ndc11', how= 'left')

              ndc11  ... cate
0     63459-0502-30  ...  rxi
1     63459-0504-30  ...  rxi
2     63459-0506-30  ...  rxi
3     63459-0508-30  ...  rxi
4     63459-0512-30  ...  rxi
...             ...  ...  ...
1023  10370-0191-05  ...  rxi
1024  00032-1708-01  ...  rxi
1025  10370-0190-01  ...  rxi
1026  00832-0302-00  ...  rxi
1027  64980-0205-01  ...  rxi

[1028 rows x 33 columns]

In [ ]:
rxi_target = rxi_info2[rxi_info2['drug'].isin(target_list[0])]
rxi_target.to_csv('/content/drive/Shareddrives/Codepresso_8/Drug_list/rxi_meta_target.csv')
rxi_list = list(rxi_target.drug.unique())

In [ ]:
top.drug

Rank
1                                           atorvastatin
2                                          levothyroxine
3                                             lisinopril
4                                metformin hydrochloride
5                                             amlodipine
                             ...
296                                      pseudoephedrine
297                                        insulin human
298                                sacubitril; valsartan
299    pancrelipase lipase; pancrelipase protease; pa...
300    brompheniramine maleate; dextromethorphan hydr...
Name: drug, Length: 300, dtype: object

In [ ]:
rxi_target = pd.read_csv("./rxi_meta_target.csv", index_col=False)
rxi_info2 = pd.read_csv("./rxi_info2.csv", index_col=False)

In [ ]:
rxi_info2.shape

(970, 17)

In [ ]:
rxi_top = rxi_info2[rxi_info2['drug'].isin(top.drug)]
rxi_top.to_csv('/content/drive/Shareddrives/Codepresso_8/Drug_list/final_data/rxi_top.csv')
rxi_top_list = list(rxi_top.drug.unique())
rxi_top

     Unnamed: 0          ndc11  ...              drug2         drug3
0             0  63459-0502-30  ...           fentanyl      fentanyl
1             1  63459-0504-30  ...           fentanyl      fentanyl
2             2  63459-0506-30  ...           fentanyl      fentanyl
3             3  63459-0508-30  ...           fentanyl      fentanyl
4             4  63459-0512-30  ...           fentanyl      fentanyl
..          ...            ...  ...                ...           ...
962        4109  59762-0540-01  ...          glipizide     glipizide
965        4187  10370-0191-05  ...          glipizide     glipizide
966        4198  00032-1708-01  ...       progesterone  progesterone
967        4236  10370-0190-01  ...          glipizide     glipizide
969        4268  64980-0205-01  ...  lithium carbonate       lithium

[490 rows x 17 columns]

In [ ]:
len(rxi_top.drug.unique()), len(rxi_target.drug.unique())

(68, 56)

In [ ]:
rxi_top_target_list = set(rxi_top.drug).union(set(rxi_target.drug))

In [ ]:
rxi_top_target = rxi_info2[rxi_info2['drug'].isin(rxi_top_target_list)]

In [ ]:
rxi_target_list = list(set(rxi_target.drug))

In [ ]:
pd.DataFrame(rxi_target_list).to_csv("./rxi_target_list.csv", index=False)

In [ ]:
rxi_top_target.loc[rxi_top_target['drug'].isin(rxi_target_list), 'caution'] = 1

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [ ]:
rxi_top_target['caution'] = 0
rxi_top_target.loc[rxi_top_target['drug'].isin(rxi_target_list), 'caution'] = 1
rxi_top_target

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1763: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

     Unnamed: 0          ndc11  ...         drug3 caution
0             0  63459-0502-30  ...      fentanyl       1
1             1  63459-0504-30  ...      fentanyl       1
2             2  63459-0506-30  ...      fentanyl       1
3             3  63459-0508-30  ...      fentanyl       1
4             4  63459-0512-30  ...      fentanyl       1
..          ...            ...  ...           ...     ...
962        4109  59762-0540-01  ...     glipizide       1
965        4187  10370-0191-05  ...     glipizide       1
966        4198  00032-1708-01  ...  progesterone       0
967        4236  10370-0190-01  ...     glipizide       1
969        4268  64980-0205-01  ...       lithium       1

[491 rows x 18 columns]

In [ ]:
rxi_top_target.caution.value_counts()

1    428
0     63
Name: caution, dtype: int64

In [ ]:
rxi_top_target.drop(columns = 'Unnamed: 0', inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

# rxi_top_target

In [ ]:
rxi_top_target= pd.read_csv('/content/drive/Shareddrives/Codepresso_8/Drug_list/final_data/rxi_top_target.csv', sep = ",")
rxi_top_target

             ndc11  ...                                           path_300
0    63459-0502-30  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
1    63459-0504-30  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
2    63459-0506-30  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
3    63459-0508-30  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
4    63459-0512-30  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
..             ...  ...                                                ...
486  59762-0540-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
487  10370-0191-05  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
488  00032-1708-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
489  10370-0190-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
490  64980-0205-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...

[491 rows x 20 columns]

In [ ]:
rxi_top_target.to_csv('/content/drive/Shareddrives/Codepresso_8/Drug_list/final_data/rxi_top_target.csv', index = False)
#rxi_top_target_list.to_csv('/content/drive/Shareddrives/Codepresso_8/Drug_list/final_data/rxi_top_target_list.csv', index = False)
rxi_top_target

NameError: ignored

In [ ]:
rxi_top_target.imprint_str.str.split(";")

0      [actiq, ]
1      [actiq, ]
2      [actiq, ]
3      [actiq, ]
4      [actiq, ]
         ...
486      [gxl, ]
487      [wpi, ]
488          NaN
489      [wpi, ]
490        [p, ]
Name: imprint_str, Length: 491, dtype: object

In [ ]:
rxi_top_target.imprint_int.str.split(";")

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
       ...
486    [2, ]
487      NaN
488      NaN
489      NaN
490      NaN
Name: imprint_int, Length: 491, dtype: object

In [ ]:
rxi_top_target.imprint.str.split(";")

0       [actiq, 200]
1       [actiq, 400]
2       [actiq, 600]
3       [actiq, 800]
4      [actiq, 1200]
           ...
962      [gxl, 2, 5]
965       [wpi, 845]
966             [sv]
967       [wpi, 844]
969         [p, 300]
Name: imprint, Length: 491, dtype: object

In [ ]:
pd.DataFrame(df.Name.str.split('_',1).tolist(),
                         columns = ['first','Last']))

In [ ]:
pd.DataFrame(rxi_top_target.imprint.str.split(";")).head(2)

        imprint
0  [actiq, 200]
1  [actiq, 400]

In [ ]:
imprint_sub = pd.DataFrame(rxi_top_target.imprint.str.split(";").tolist()).head(2)

In [ ]:
rxi_top_target.imprint.str.split(";").tolist().apply(lambda x : x)

In [ ]:
rxi_top_target.imprint.str.split(";", 1).tolist()

[['actiq', '200'],
 ['actiq', '400'],
 ['actiq', '600'],
 ['actiq', '800'],
 ['actiq', '1200'],
 ['actiq', '1600'],
 ['e615'],
 ['e613'],
 ['v', '3566'],
 ['mutual', '100;mutual;100'],
 ['mutual', '105; mutual;105'],
 ['dan', '5440;dan;5440'],
 ['gg', '606;gg;606'],
 ['93', '3147;93;3147'],
 ['mylan', '143;mylan;143'],
 ['93', '3109;93;3109'],
 ['93', '3145;93;3145'],
 ['rx693', 'rx693'],
 ['g', '300;mg;5010'],
 ['93', '5256;93;5256'],
 ['par', '726;par;726'],
 ['apo', '010'],
 ['andrx', '640;40;mg'],
 ['ip', '101;ip;101'],
 ['r', '2666;r;2666'],
 ['r', '667;r;667'],
 ['d', '26'],
 ['z', '4030;z;4030'],
 ['taro', 'phn;100;taro;phn;100'],
 ['rp', '1;25'],
 ['54', '602;54;602'],
 ['mylan', '2537;mylan;2537'],
 ['n', '940;200'],
 ['g', '150;mg;3328'],
 ['cor', '153;cor;153'],
 ['93', '3171;93;3171'],
 ['dan', '5708;dan;5708'],
 ['g', '5026'],
 ['mylan', '2264;mylan;2264'],
 ['500', 'lupin;500;lupin'],
 ['r', '665;r;665'],
 ['barr', '323;25'],
 ['barr', '302;50'],
 ['z', '4029;z;4029'],
 ['mylan', '143;mylan;143'],
 ['ku', '136'],
 ['mylan', '1650;mylan;1650'],
 ['mylan', '1700;mylan;1700'],
 ['tcl', '1222'],
 ['tl', '383;tl;383'],
 ['mylan', '2260;mylan;2260'],
 ['tl', '384;tl;384'],
 ['mylan', '2264;mylan;2264'],
 ['rdy', '341'],
 ['rdy', '339'],
 ['a44'],
 ['adoxa', '150mg'],
 ['rdy', '340'],
 ['01a'],
 ['200', 'cti;111'],
 ['shire', 'carbatrol;200;mg'],
 ['watson', '3219'],
 ['b', '073'],
 ['dan', '3120;dan;3120'],
 ['tap', 'prevacid;30'],
 ['watson', '411;100;mg'],
 ['west', 'ward;3142'],
 ['93', '7385;93;7385'],
 ['g', '0533;g;0533'],
 ['b', '074'],
 ['a45'],
 ['cleocin', '75;mg;cleocin;75;mg'],
 ['d', '03'],
 ['ip', '103;ip;103'],
 ['ig323', '400;mg'],
 ['ig321', '100mg'],
 ['watson', '347;12;5;mg'],
 ['mylan', '147;mylan;147'],
 ['gg', '517;gg;517'],
 ['watson', '801;50;mg'],
 ['rdy', '398'],
 ['tap', 'prevacid;15'],
 ['ku', '114'],
 ['omeprazole', '10;mg;r;157'],
 ['par', '455'],
 ['omeprazole', '40;mg;r;159'],
 ['e', '122'],
 ['54', '794;54;794'],
 ['andrx', '559'],
 ['andrx', '560'],
 ['54', '145;54;145'],
 ['rp', '5'],
 ['lupin', 'ramipril;10mg'],
 ['rp', '10'],
 ['gg', '614;gg;614'],
 ['25', 'ti'],
 ['tl', '386;tl;386'],
 ['gg', '624;gg;624'],
 ['mylan', '1570;mylan;1570'],
 ['tl', '385;tl;385'],
 ['gg', '621;gg;621'],
 ['omeprazole', '20;mg;r;158'],
 ['mylan', '6150;mylan;6150'],
 ['93', '7386;93;7386'],
 ['amox', '250;gg;848'],
 ['lilly', '3270;60;mg'],
 ['lilly', '3240;30;mg'],
 ['gsk', 'coreg;cr;80;mg'],
 ['ccc', '250;ccc;250'],
 ['lupin', 'cefdinir'],
 ['watson', '3220'],
 ['nc', '200'],
 ['nc', '300'],
 ['dilantin', '30;mg'],
 ['dilantin', '100;mg'],
 ['wc', '731;wc;731'],
 ['lilly', '3235;20;mg'],
 ['w', 'effexorxr;150'],
 ['w', 'effexorxr;75'],
 ['w', 'effexor;xr;37.5'],
 ['dan', '5535;dan;5535'],
 ['lotrel', '0379'],
 ['lotrel', '0384'],
 ['lotrel', '2265'],
 ['monodox', '75;m;075'],
 ['pfizer', 'pgn;150'],
 ['pfizer', 'pgn;300'],
 ['pfizer', 'pgn;75'],
 ['pfizer', 'pgn;200'],
 ['macrodantin', '25;mg;0149;0007'],
 ['pfizer', 'pgn;100'],
 ['pfizer', 'pgn;50'],
 ['pfizer', 'pgn;225'],
 ['monodox', '100;m;259'],
 ['d', '04'],
 ['entocort', 'ec;3;mg'],
 ['93', '7370;93;7370'],
 ['teva', '7371'],
 ['teva', '7372'],
 ['teva', '7373'],
 ['teva', '3145'],
 ['teva', '3147'],
 ['teva', '3107'],
 ['teva', '3109'],
 ['gs', '7cz'],
 ['gsk', 'coreg;cr;10;mg'],
 ['gsk', 'coreg;cr;20;mg'],
 ['dyazide', 'sb;dyazide;sb'],
 ['wellcome', 'zovirax;200'],
 ['nexium', '20mg'],
 ['e', '882;e;882'],
 ['s429', '250;mg;2010'],
 ['s429', '500;mg'],
 ['phoslo', '667mg'],
 ['macrodantin', '50;mg;52427;287'],
 ['valeant', 'pf;0844'],
 ['ip', '212;ip;212'],
 ['nexium', '40;mg'],
 ['top', '15;mg'],
 ['gg', '623;gg;623'],
 ['2', 'mg'],
 ['6', 'mg'],
 ['4', 'mg'],
 ['40'],
 ['30', 'mg;novel;123'],
 ['mutual', '866;mutual;866'],
 ['gg', '531;gg;531'],
 ['teva', '7335'],
 ['teva', '7670'],
 ['teva', '2080'],
 ['teva', '7336'],
 ['teva', '7671'],
 ['teva', '7370'],
 ['teva', '4030'],
 ['teva', '3171'],
 ['teva', '5256'],
 ['teva', '4029'],
 ['apo', '020'],
 ['apo', '040'],
 ['z', 'zenith;50;mg;2130'],
 ['z', 'zenith;100;mg;2131'],
 ['93', '3160;93;3160'],
 ['barr', '324;100'],
 ['barr', '302;50'],
 ['barr', '323;25'],
 ['93', '7351;93;7351'],
 ['cephalon', '30;mg'],
 ['93', '7350;93;7350'],
 ['15mg', 'cephalon'],
 ['i', '4336;1;mg'],
 ['i', '4338;5;mg'],
 ['i', '4339;10;mg'],
 ['barr', '808'],
 ['375', 'mg;pliva'],
 ['93', '7436;93;7436'],
 ['93', '7437;93;7437'],
 ['93', '7438;93;7438'],
 ['93', '7384;93;7384'],
 ['barr', '934'],
 ['barr', '454'],
 ['barr', '936'],
 ['barr', '935'],
 ['lofibra', '134;mg;gate;323'],
 ['adipex', 'p;37;5'],
 ['lofibra', '67;mg;gate;322'],
 ['lofibra', '200;mg;gate;324'],
 ['93', '5514;93;5514'],
 ['93', '5513;93;5513'],
 ['93', '5512;93;5512'],
 ['apo', 't4'],
 ['apo', 't6'],
 ['93', '7351;93;7351'],
 ['teva', '3109'],
 ['teva', '7542'],
 ['teva', '7543'],
 ['teva', '7544'],
 ['l', '2'],
 ['l', '5'],
 ['apo', '042'],
 ['i', '98'],
 ['i', '97'],
 ['rdy', '586'],
 ['entocortec', '3;mg'],
 ['801'],
 ['g', 'm'],
 ['sandoz', '663;sandoz;663'],
 ['7767', '100'],
 ['7767', '200'],
 ['spd417', 'spd417;200;mg'],
 ['2890', '2890'],
 ['tap', '30'],
 ['par', '727;par;727'],
 ['tap', '60'],
 ['s433', '200;mg'],
 ['s433', '300;mg'],
 ['lilly', '3270;60;mg'],
 ['mylan', '6089,mylan;6089'],
 ['mylan', 'fe;67;mylan;fe;67'],
 ['mylan', 'fe;134;mylan;fe;134'],
 ['rdy', '587'],
 ['x', '02'],
 ['g406', 'g'],
 ['216'],
 ['214'],
 ['506', 'amneal'],
 ['rdy', '399'],
 ['pfizer', 'pgn;25'],
 ['98', 'h'],
 ['g', '248;150'],
 ['natco', '30'],
 ['97', 'h'],
 ['macrodantin', '100;mg;52427;286'],
 ['2891', '2891'],
 ['4', 'mg'],
 ['za64', '25;mg'],
 ['2', 'mg'],
 ['apo', 't2'],
 ['rp', '2;5'],
 ['lu', 'e13'],
 ['lu', 'e16'],
 ['667', 'mg;ig;377'],
 ['lu', 'e14'],
 ['lu', 'e12'],
 ['7767', '200'],
 ['250', 'lupin;250;lupin'],
 ['fioricet', 'fioricet'],
 ['x', '03'],
 ['x', '01'],
 ['802'],
 ['54', '702;54;702'],
 ['wc', '400;mg'],
 ['mylan', 'fe;200;mylan;fe;200'],
 ['40'],
 ['w', 'effexor;xr;75'],
 ['watson', '410;50;mg'],
 ['lu', 'e;15'],
 ['7767', '200'],
 ['7767', '200'],
 ['7767', '100'],
 ['aa', '820'],
 ['dan', '3120;dan;3120'],
 ['6451', '40;mg'],
 ['lu', 'c22'],
 ['215'],
 ['gg638', 'gg638'],
 ['fl', '145'],
 ['macrobid', '52427;285'],
 ['mylan', '1560;mylan;1560'],
 ['lannett', '1632'],
 ['93', '5295;93;5295'],
 ['barr', '658'],
 ['93', '5292;93;5292'],
 ['93', '5293;93;5293'],
 ['93', '5296;93;5296'],
 ['93', '5297;93;5297'],
 ['93', '5298;93;5298'],
 ['teva', '7306'],
 ['teva', '7165'],
 ['teva', '7166'],
 ['teva', '7170'],
 ['6450', '20;mg'],
 ['teva', '01a'],
 ['u', '130'],
 ['c', '39'],
 ['e122'],
 ['tl', '382;tl;382'],
 ['h', '103'],
 ['e613', 'e613'],
 ['7767', '100'],
 ['g231', 'g'],
 ['west', 'ward;3142'],
 ['lupin', 'ramipril;5mg'],
 ['nc', '100'],
 ['apo', 'c100'],
 ['j', '03'],
 ['ome', '20;ome;20'],
 ['rdy', '493'],
 ['apo', 'f130'],
 ['d', '02'],
 ['130', 'antara;lupin'],
 ['apo', 'c200'],
 ['mylan', '3422;mylan;3422'],
 ['e', '73'],
 ['e', '89'],
 ['mylan', '6896;mylan;6896'],
 ['mylan', '6895;mylan;6895'],
 ['mylan', '6897;mylan;6897'],
 ['667', 'mg;ig377'],
 ['lannett', '1383'],
 ['za', '37;150;mg'],
 ['h', '71'],
 ['cipla', '421;200;mg'],
 ['amneal', '542'],
 ['002', '002'],
 ['gld', '40'],
 ['hp', '10;hp;10'],
 ['d', '03'],
 ['g', '246;50'],
 ['g248', '150'],
 ['ab', '6'],
 ['ig321', '100mg'],
 ['ig322', '300mg'],
 ['rdy', '493'],
 ['b', '748'],
 ['b', '747'],
 ['156', 'a'],
 ['gld', '40'],
 ['spn', '25'],
 ['pad', '0181'],
 ['402', '402'],
 ['west', 'ward;118'],
 ['e', '74'],
 ['ipx066', '95'],
 ['za', '43;1;25;mg'],
 ['d', '08'],
 ['lupin', 'ramipril;2;5;mg'],
 ['apo', 'c300'],
 ['west', 'ward;118'],
 ['ome', '10;ome;10'],
 ['b', '746'],
 ['mylan', '8030;mylan;8030'],
 ['ram', '2;5;mg'],
 ['j', '02'],
 ['a44'],
 ['e99'],
 ['j', '01'],
 ['d', '07'],
 ['cd', '129'],
 ['7767', '100'],
 ['plaquenil'],
 ['procardia', 'pfizer;260'],
 ['asc', '105'],
 ['r', '497'],
 ['758'],
 ['asacol', 'ne'],
 ['wc', '800'],
 ['mb', '111'],
 ['l008'],
 ['ucb', '500xr'],
 ['gx', 'ce2'],
 ['lamictal', 'xr;300'],
 ['93', '6'],
 ['mb-111'],
 ['imi', '10'],
 ['500', '20'],
 ['valtrex', '1;gram'],
 ['valtrex', '500;mg'],
 ['tv', 'a18'],
 ['tv', '7796'],
 ['tv', '7795'],
 ['93', '658'],
 ['93', '657'],
 ['93', '5'],
 ['50', 'mg'],
 ['100', 'mg'],
 ['25', 'mg'],
 ['pa83'],
 ['pa46'],
 ['tv', 'a19'],
 ['pa140'],
 ['h118'],
 ['r', '530'],
 ['600'],
 ['r50'],
 ['x592'],
 ['547'],
 ['h119'],
 ['133'],
 ['136'],
 ['ak2'],
 ['25', 'mg'],
 ['50', 'mg'],
 ['100', 'mg'],
 ['tv', '5655'],
 ['p51'],
 ['p', '1'],
 ['pa46'],
 ['194'],
 ['a', '75'],
 ['m05'],
 ['r1'],
 ['gg', '738'],
 ['r', '550'],
 ['r', '551'],
 ['m', '475'],
 ['m', '482'],
 ['m', '495'],
 ['44', '227'],
 ['wpi', '339'],
 ['v', '4'],
 ['wpi', '338'],
 ['p', '75'],
 ['wpi', '845'],
 ['wpi', '844'],
 ['wpi', '845'],
 ['wpi', '900'],
 ['m', 'p4'],
 ['ku', '271'],
 ['ku', '272'],
 ['ku', '270'],
 ['g', '90'],
 ['g', '60'],
 ['g', '30'],
 ['ku', '262'],
 ['os', '303'],
 ['os', '302'],
 ['os', '304'],
 ['os', '301'],
 ['lamictal', 'xr;50'],
 ['glipizide', 'xl;10'],
 ['lamictal', 'xr;25'],
 ['lamictal', 'xr;50'],
 ['lamictal', 'xr;25'],
 ['lamictal', 'xr;50'],
 ['lamictal', 'xr;100'],
 ['lamictal', 'xr;200'],
 ['lamictal', 'xr;50'],
 ['lamictal', 'xr;100'],
 ['wellbutrin', 'sr;100'],
 ['wellbutrin', 'sr;150'],
 ['wellbutrin', 'sr;200'],
 ['759'],
 ['l'],
 ['a102'],
 ['cti', '103'],
 ['gxl', '5'],
 ['gxl', '10'],
 ['m', 'o17'],
 ['m', 'o5'],
 ['m', 'o10'],
 ['m', 'p3'],
 ['os', '304'],
 ['sz', '788'],
 ['lamictal', 'xr;100'],
 ['t', '400;mg'],
 ['t', '100;mg'],
 ['g', 'ds;50'],
 ['ak'],
 ['a', '101'],
 ['gg', '739'],
 ['m', 'p5'],
 ['eln', '30'],
 ['alavert', 'd12'],
 ['sz', '787'],
 ['p', '50'],
 ['sv'],
 ['gxl', '2;5'],
 ['wpi', '845'],
 ['sv'],
 ['wpi', '844'],
 ['p', '300']]

In [ ]:
rxi_top_target['imprint'][0].
rxi_info_target3['drug2'] = rxi_info_target3['name'].apply(lambda x : drug_name(x))

'actiq;200'

In [ ]:
def find_str(x):
  re.search('[A-Z|a-z]+', x)
#String target = myData.replaceAll("[^']*(?:'(.*?)')?.*", "$1");
#".*'([^']*)'.*"
#data["Name"].str.find(sub, start)
mask = np.column_stack([df[col].str.contains(r"\^", na=False) for col in df])
df.loc[mask.any(axis=1)]
df.apply(lambda row: row.astype(str).str.contains('TEST').any(), axis=1)

df['Country'] = (df.Name.str.lower()
                        .str.extract(r'inf(.*?)_')
                        .replace('', float('nan'))
                        .fillna('No_Country'))

import re
df['Country'] = ["".join(re.findall(r'inf(.*?)_', i)) for i in df['Name']]

pd.DataFrame(df.Name.str.split('_',1).tolist(),
                         columns = ['first','Last']))

In [ ]:
def find_str(x):
  re.search('\S+', x)

In [ ]:
def drug_name(x):
  re.search('[A-Z|a-z|]{3,}[A-Z|a-z|\s]{3,}', x)

In [ ]:
#rxi_top_target['imprint_int']= ["".join(re.findall(r'\d+\;', i)) for i in rxi_top_target['imprint']]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
rxi_top_target['imprint_int']= [";".join(re.findall(r'\d+', i)) for i in rxi_top_target['imprint']]

In [ ]:
rxi_top_target['imprint_int']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
486     2;
487    NaN
488    NaN
489    NaN
490    NaN
Name: imprint_int, Length: 491, dtype: object

In [ ]:
rxi_top_target['imprint_int2']

0       200
1       400
2       600
3       800
4      1200
       ...
486     2;5
487     845
488
489     844
490     300
Name: imprint_int2, Length: 491, dtype: object

In [ ]:
#rxi_top_target['imprint_str']= ["".join(re.findall(r'[A-Z|a-z]+\;', i)) for i in rxi_top_target['imprint']]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
rxi_top_target['imprint_str']= [";".join(re.findall(r'[A-Z|a-z]+', i)) for i in rxi_top_target['imprint']]

In [ ]:
rxi_top_target['imprint_str']

0      actiq
1      actiq
2      actiq
3      actiq
4      actiq
       ...
486      gxl
487      wpi
488       sv
489      wpi
490        p
Name: imprint_str2, Length: 491, dtype: object

In [ ]:
rxi_top_target.head(40)

            ndc11  ...                                           path_300
0   63459-0502-30  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
1   63459-0504-30  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
2   63459-0506-30  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
3   63459-0508-30  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
4   63459-0512-30  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
5   63459-0516-30  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
12  00185-0615-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
13  00185-0613-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
14  00603-3855-21  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
15  53489-0118-02  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
16  53489-0119-02  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
17  00591-5440-50  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
21  00781-2074-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
22  00093-3147-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
24  00378-0143-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
27  00093-3109-05  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
28  00093-3145-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
33  63304-0693-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
34  59762-5010-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
35  00093-5256-68  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
37  49884-0726-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
39  60505-0145-00  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
40  62037-0640-30  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
46  53746-0101-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
47  00228-2666-11  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
48  00228-2667-11  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
49  65862-0113-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
50  00093-4030-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
51  51672-4111-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
53  16252-0570-30  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
54  00054-0109-25  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
55  00378-2537-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
56  00093-8940-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
57  59762-3328-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
58  00781-2112-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
59  00093-3171-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
60  00591-5708-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
61  59762-5026-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
62  00378-2264-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...
63  68180-0122-01  ...  /content/drive/Shareddrives/Codepresso_8/rxima...

[40 rows x 20 columns]

In [ ]:
rxi_top_target['imprint'][rxi_top_target.imprint.str.contains('\d+', na=False)]

0       actiq;200
1       actiq;400
2       actiq;600
3       actiq;800
4      actiq;1200
          ...
960          p;50
962       gxl;2;5
965       wpi;845
967       wpi;844
969         p;300
Name: imprint, Length: 481, dtype: object

In [ ]:
rxi_top_target.imprint.str.contains('\S+', na=False)

0      True
1      True
2      True
3      True
4      True
       ...
962    True
965    True
966    True
967    True
969    True
Name: imprint, Length: 491, dtype: bool

In [ ]:
imprint_sub.str.sxtract

       0    1     2     3     4     5
0  actiq  200  None  None  None  None
1  actiq  400  None  None  None  None

In [ ]:
def drug_name(x):
  re.search('[A-Z|a-z|]{3,}[A-Z|a-z|\s]{3,}', x)

TypeError: ignored

In [ ]:
re.search('[A-Z|a-z]+\;', 'actiq;200;momo;10')[0]

'actiq;'

In [ ]:
re.search('[A-Z|a-z]+', 'actiq;200;momo;10')[0]

'actiq'

In [ ]:
re.search('\D+[^;]+', 'actiq;200;momo;10')[0]

'actiq;200'

In [ ]:
re.search('\d+', 'actiq;200;momo;10')[0]

'200'

In [ ]:
re.search('\D+', 'actiq;200;momo;10')[0]

'actiq;'

In [ ]:
re.search('[A-Z|a-z]+', 'actiq;200;momo;10')[0]

'actiq'

In [ ]:
def find_str(x):
  re.search('[A-Z|a-z]+', x)

def find_int(x):
  re.search('\d+', x)
  
find_str('actiq;200;momo;10')

In [ ]:
find_int('actiq;200;momo;10')

In [ ]:
re.search('([\D]])+(;)', 'actiq;200;momo;10')[0]

TypeError: ignored

In [ ]:
(?<=a href=")[^http](.*?)(\.html")
(?<=a href=")(?!http)[^"]*\/([^"]+)(?=">)

In [ ]:
re.search(",*'(^[A-Z|a-z]+)',*", 'actiq;200;momo;10')

In [ ]:
rxi_top_target['imprint_str'].value_counts()

teva;                  26
mylan;mylan;           18
lamictal;xr;           11
apo;                   11
barr;                  11
                       ..
cor;cor;                1
asc;                    1
eln;                    1
entocort;ec;            1
cleocin;mg;cleocin;     1
Name: imprint_str, Length: 125, dtype: int64

In [ ]:
imprint_str_sub = pd.DataFrame(rxi_top_target['imprint_str'].str.split(";").tolist(), columns = ['imprint_str1','imprint_str2', 'imprint_str3','imprint_str4'])

In [ ]:
imprint_int_sub = pd.DataFrame(rxi_top_target['imprint_int'].str.split(";").tolist(), columns = ['imprint_int1','imprint_int2', 'imprint_int3','imprint_int4'])

In [ ]:
imprint_sub = pd.DataFrame(rxi_top_target['imprint'].str.split(";").tolist(), columns = ['print_0','print_1', 'print_2', 'print_3' ,'print_4','print_6']).head(10)

In [ ]:
pd.DataFrame(rxi_top_target['imprint'].str.split(";").tolist(), columns = ['print_0','print_1', 'print_2', 'print_3' ,'print_4','print_6']).head(10)

In [ ]:
rxi_imprint = pd.DataFrame(rxi_top_target['imprint'].str.split(";").tolist(), columns = ['print_0','print_1', 'print_2', 'print_3' ,'print_4','print_6'])

In [ ]:
rxi_imprint.shape, rxi_top_target.shape

((491, 6), (491, 20))

In [ ]:
pd.concat([rxi_top_target, rxi_imprint], axis = 1).drop(columns = ['drug3', 'imprint_int2', 'imprint_str2']).to_csv("./rxi_top_target.csv", index=False)

In [ ]:
rxi_top_target = pd.concat([rxi_top_target, rxi_imprint], axis = 1).drop(columns = ['drug3', 'imprint_int2', 'imprint_str2'])

In [ ]:
imprint_sub =  pd.concat([imprint_str_sub, imprint_int_sub], axis = 1) #]).to_csv("./rxi_top_target.csv", index=False)

In [ ]:
pd.concat([rxi_top_target, imprint_sub], axis = 1).to_csv("./rxi_top_target_imprint.csv", index=False)

In [ ]:
rxi_top_target['path_300'] = rxi_top_target['nlmImageFileName'].apply(lambda x : img_path_base + x)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
img_path_base = '/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_rximage/images/gallery/300/'

In [ ]:
rxi_top_target.head(3).path_300[1]

'/content/drive/Shareddrives/Codepresso_8/rximage_set/imageset_rximage/images/gallery/300/63459-0504-30_nlmimage10_8841c43e.jpg'

In [ ]:
rxi_top_target.to_csv("./rxi_top_target.csv", index=False)

In [ ]:
!pwd

/content/drive/Shareddrives/Codepresso_8/Drug_list

In [ ]:
len(set(dur_list).difference(set(rxi_list)))

172

In [ ]:
len(set(dur_list).intersection(set(rxi_list)))

76

In [ ]:
inter_dr = set(dur_list).intersection(set(rxi_list))

In [ ]:
len((set(dur_list).union(set(rxi_list))).union(set(drug_101.name)))

771

In [ ]:
len(set(dur_list).union(set(rxi_list)))

684

In [ ]:
len(set(dur_list).intersection(set(drug_101.name)))

0

In [ ]:
len(set(rxi_list).intersection(set(drug_101.name)))

14

In [ ]:
len(set(drug_101.name).difference(inter_dr))

101

In [ ]:
len(set(drug_101.name).difference(rxi_list))

87

In [ ]:
len(inter_dr)

76

In [ ]:
len(set(drug_101.name))

101

In [ ]:
drug_101.name

0        aceclofenac
1      acetaminophen
2         alprazolam
3         amiodarone
4      amitriptyline
           ...
96         triazolam
97       venlafaxine
98         verapamil
99       ziprasidone
100         zolpidem
Name: name, Length: 101, dtype: object

In [ ]:
inter_dr

{'Acetazolamide',
 'Acitretin',
 'Alprazolam',
 'Amantadine',
 'Amiloride',
 'Amiodarone',
 'Amitriptyline',
 'Aspirin',
 'Azithromycin',
 'Calcitriol',
 'Carbamazepine',
 'Chlorpromazine',
 'Chlorthalidone',
 'Citalopram',
 'Clarithromycin',
 'Clomipramine',
 'Dexamethasone',
 'Diclofenac',
 'Diethylpropion',
 'Diflunisal',
 'Diltiazem',
 'Dipyridamole',
 'Doxepin',
 'Doxycycline',
 'Erythromycin',
 'Esomeprazole',
 'Fluconazole',
 'Fluoxetine',
 'Fluvoxamine',
 'Gemfibrozil',
 'Glipizide',
 'Haloperidol',
 'Hydrochlorothiazide',
 'Hydrocortisone',
 'Hydroxyzine',
 'Ibuprofen',
 'Imipramine',
 'Isosorbide',
 'Isotretinoin',
 'Itraconazole',
 'Ketoconazole',
 'Ketoprofen',
 'Ketorolac',
 'Lamivudine',
 'Lovastatin',
 'Metformin',
 'Methotrexate',
 'Methylprednisolone',
 'Metolazone',
 'Metronidazole',
 'Minocycline',
 'Mirtazapine',
 'Nelfinavir',
 'Nitroglycerin',
 'Nortriptyline',
 'Omeprazole',
 'Paroxetine',
 'Perphenazine',
 'Phentermine',
 'Pimozide',
 'Piroxicam',
 'Pseudoephedrine',
 'Rabeprazole',
 'Risperidone',
 'Rosuvastatin',
 'Sertraline',
 'Simvastatin',
 'Spironolactone',
 'Sulfamethoxazole',
 'Sumatriptan',
 'Tacrolimus',
 'Ticagrelor',
 'Tretinoin',
 'Triazolam',
 'Trifluoperazine',
 'Verapamil'}

In [ ]:
!pwd

/content/drive/Shareddrives/Codepresso_8/Drug_list